tjcsl/ion

intranet/static/css/login.css
Addresses #373
Right now, the layout of the login page is extremely clean. However, until he uploaded that screenshot I had never even noticed those links. With just a little bit of change to the font size and padding a lot more people will probably notice it with minimal effect on the nice appearance that you guys currently have. Maybe try changing the footer css block to the following:
```css
.footer {
position: fixed;
bottom: 0;
padding: 0 0 3px 6px;
font-size: 13px;
color: gray;
z-index: 99;
text-align: left;
width: 100%;
background: rgba(242,242,242,.5);
}
```
Differences: (click on images, fullscreen makes difference easier to see)
It's a subtle difference, but it may be enough to give the footer more presence
=> Minor change to login screen footer 

intranet/static/js/vendor/jquery.timeago.js, intranet/templates/announcements/announcement.html, intranet/templates/eighth/signup_widget.html, intranet/templates/eighth/take_attendance.html, intranet/templates/events/event.html, intranet/templates/polls/poll.html
if javascript is disabled for some reason, the solution will fall back to the server generated timeago and the title will be the actual time
i would like to add this to the filesystem folders/files, but this would conflict with another one of my pull requests
i didn't include {{ block.super }} in some of the cases since i don't think there was anything to super and when i did it it threw an error
=> added client side timeago

intranet/apps/files/views.py
if dir was set to /R/ then the page would constantly redirect to the same page until 400 bad request
this was because code checked if /R started with /R/, since only one path was normalized
since /R does not start with /R/, then it would redirect to the same page
fixed by normalizing the working directory path
=> fixed 400 bad request bug

intranet/templates/feedback/form.html
Changes the label on the button from "Submit Query" to simply "Submit", because from the user's point of view feedback is often not a query.
=> Change feedback form button to "Submit"

intranet/static/js/ads.js, intranet/static/js/showads.js, intranet/templates/auth/login.html
On the login page, if users have an adblocker active (prevents ads.js or shows.js from running), then a red banner will display on the top of the saying: 
We depend on revenue from advertisements to keep ION running for users like you. 
Without them, we couldn't remain free and accesible to everyone. 
If you depend on ION, please consider supporting us by disabling your ad blocker.
This only displays on the login page, and wraps behind the login screen on mobile (does not obstruct anything)
=> Adblock Detect (for April Fool's Day)

intranet/apps/search/views.py
Advanced search with "last" attribute wasn't working because "last" was mapping to "sn", instead of "last_name". This fixes behavior so using "last:thistlethwaite" has identical behavior to "lastname:thistlethwaite"
@ovkulkarni
=> Fix "last" mapping to "sn" in advanced search

Ion.egg-info/PKG-INFO, Vagrantfile, config/provision_vagrant.sh, setup.py
Currently, `vagrant ssh` logs in as `vagrant`, the default Vagrant configuration.  This is not expected behavior because all files in the intranet directory are owned by `ubuntu`.
=> Make vagrant ssh as ubuntu

setup.py
In pip>=10.0.0, the pip team got rid of access to pip.download and pip.req  ([https://github.com/pypa/pip/issues/4696](https://github.com/pypa/pip/issues/4696)).  Currently, builds are failing due to this issue.
=> Remove dependence on unsupported pip API

Ion.egg-info/SOURCES.txt, cron/oauth-cleartokens.sh, intranet/settings/__init__.py
Currently, [https://ion.tjhsst.edu/oauth/authorized_tokens](https://ion.tjhsst.edu/oauth/authorized_tokens) is a huge list of authorized tokens, where almost all of them will never be used again.  Sites using OAuth like Director and TJSTAR don't use tokens after the user logs out.
This PR will use a cron job to delete tokens more than 30 days old.
=> Clear unused OAuth tokens

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, intranet/apps/files/views.py, requirements.txt
pycrypto has had no new releases since October of 2013.  [pycryptodome](https://github.com/Legrandin/pycryptodome) is a fork of pycrypto that is actively maintained. pycryptodome should be a simple drop-in replacement.
=> Move  from pycrypto to pycryptodome

Vagrantfile, config/devconfig.json.sample
* Bump Vagrant requirement because of change in Vagrant download URL [described here](https://github.com/hashicorp/vagrant/issues/9442)
* Add option to use the VPN
* Add option to use NFS
=> Vagrant fixes

intranet/static/css/login.scss, intranet/static/css/page_base.scss, intranet/static/js/common.js
CSS transforms can now be applied without breaking the layout.
Previously, using a transform on body would interfere with the position of the header. For example, here is a `transform: scale(1);` (which shouldn't do anything): 
Now, transforms can be applied to body while maintaining the proper layout. Here is the same `transform: scale(1);`: 
This means that things like [do a barrel roll](https://github.com/tjcsl/ion/blob/master/intranet/static/js/common.js#L155-L160) will now work properly.
=> Fixed CSS transform interfering with layout

intranet/templates/polls/vote.html
For some reason, the "type" attribute is not set for "Short answer" inputs. This means that the custom styles for text inputs are not applied, which slightly changes the way they are displayed.
=> Set type attribute on poll short answer inputs

intranet/apps/preferences/forms.py, intranet/apps/preferences/tests.py, intranet/apps/preferences/views.py
Makes it possible to save the preferences page without setting a bus route if the user hasn't done that yet. Also actually add some tests for the bus route form.
=> Allow the user to set a null bus route on the preferences page

intranet/static/css/eighth.profile.scss, intranet/templates/eighth/activity.html
These are lumped together simply because neither is big enough to be a separate PR.
The `overflow-x` property was set to `scroll` in 598000f (the blame says it was f74d249, but that commit just changed the formatting). I'm not sure what the rationale was, but I don't think it's necessary.
=> Eighth page tweaks

intranet/apps/announcements/views.py, intranet/apps/auth/backends.py, intranet/apps/auth/views.py, intranet/apps/dashboard/views.py, intranet/apps/eighth/models.py, intranet/apps/eighth/views/admin/groups.py, intranet/apps/eighth/views/admin/rooms.py, intranet/apps/eighth/views/admin/scheduling.py, intranet/apps/eighth/views/attendance.py, intranet/apps/eighth/views/profile.py, intranet/apps/files/views.py, intranet/apps/notifications/emails.py, intranet/apps/polls/views.py, intranet/apps/preferences/views.py, intranet/apps/printing/views.py, intranet/apps/schedule/views.py, intranet/apps/search/views.py, intranet/apps/users/models.py, intranet/utils/helpers.py
Currently, the interpolation of variables in log messages is very non-standardized. This standardizes on using the interpolation built into `logging.Logger`.
Note: This was originally part of #611, but it was split out because it is more controversial than the changes in that PR.
=> Use logging.Logger's built-in string interpolation

.gitignore, .travis.yml, config/provision_vagrant.sh
[Ruby Sass is deprecated](https://sass-lang.com/ruby-sass). The new standard implementation is Dart Sass. This PR installs the Node.js-compiled version (Dart can compile to JavaScript).
Dart Sass [is not completely backwards-compatible](https://github.com/sass/dart-sass#behavioral-differences-from-ruby-sass), but it seems that Ruby Sass has deprecated/removed almost all of the features that Dart Sass lacks. In addition, we do not use many of Sass's features, so this switch should not change Ion's behavior. (Testing also shows that Dart Sass compiles all of the `static/css/*.scss` files without complaint.)
The switch will also require changes to the Ion production environment, so this PR should not be merged until a plan for said changes is in place.
Note that if you have a development …
=> Switch development environments and Travis build from Ruby Sass to Dart Sass

intranet/static/css/schedule.scss
Currently becomes misaligned when the screen gets too wide.
=> Fix alignment of schedule under day type name in calendar view

intranet/apps/users/models.py, intranet/apps/users/tests.py
Currently, the `User.permissions` property lists all the `UserProperties` object's fields and iterates through them to find the permission fields and add them to the dictionary. This should be a more efficient method.
=> Generate a dictionary listing permission names at class definition

intranet/static/js/eighth/waitlist.toggle.js, intranet/templates/eighth/admin/distribute_group.html
Many such actions already require confirmation, but there are some that do not. This PR fixes the two that I was able to find.
=> Require confirmation for admin actions with potentially undesirable consequences 

intranet/utils/date.py
Also took this opportunity to set explicit 00:00:00 times for the `datetime.datetime`s return by `get_date_range_this_year()`.
Note: @theo-o originally tracked down the bug to this function.
=> Fix the build during July

.travis.yml
Some checks had to be disabled to get it to pass. They indicate items to be worked on.
=> Add Pylint check to Travis build

.travis.yml, Ion.egg-info/PKG-INFO, README.rst, Vagrantfile, config/ion_env_setup.sh, config/provision_vagrant.sh, setup.py
Drops Python 3.5 support.
To test,
```bash
vagrant destroy
vagrant up && vagrant reload
```
Fixes #675
=> Upgrade Vagrant to bionic

.travis.yml
Since the errors from pylint don't differ (at least substantially) from one Python version to another, we should only run pylint once in the test suite.  This would shave off about 3 minutes from the test matrix.
=> build: only run pylint on one python version

intranet/middleware/access_log.py, intranet/settings/__init__.py
We should omit automated user agents in the Ion `app_access.log` file. This PR also sets up weekly rotations of the logs.
=> Update Ion logging

intranet/apps/announcements/notifications.py, intranet/apps/users/models.py, intranet/apps/users/tests.py
When sending email notifications, we should first try the user's set primary email address before falling back. This PR also does some refactoring.
Fixes #600
=> Respect user's primary email for notifications

intranet/apps/preferences/forms.py, intranet/apps/preferences/tests.py, intranet/apps/preferences/views.py
Blocks users from setting an `fcpsschools.net` address via preferences.
Fixes #599
=> Prohibit setting fcpsschools.net as an email

intranet/apps/auth/views.py
This was a regression accidentally introduced when adding dark mode patterns.
=> Make login screen background patterns appear when not in dark mode

intranet/settings/__init__.py
I missed a comma when I rebased `dark-mode` against `dev` and resolved the conflicts to make it mergeable.
=> Fix dark mode stylesheet names

intranet/apps/eighth/views/admin/general.py, intranet/templates/eighth/admin/dashboard.html
eighth_dashboard by more than 60% for loading # of users per Group by annotating the user_set count instead of full prefetchs.
(Based on timings from sqldebugshell)
```
>>> before=25.49+1.98
>>> after=8.36+1.6
>>> 1-(after/before)
0.6374226428831453
```
=> perf(eighth): improve SQL queries for

intranet/apps/announcements/notifications.py, intranet/apps/eighth/models.py, intranet/apps/eighth/views/admin/attendance.py, intranet/apps/eighth/views/admin/groups.py, intranet/apps/feedback/views.py, intranet/apps/users/models.py, intranet/apps/users/tests.py, intranet/templates/users/profile.html
The main changes:
* `User.tj_email` and `User.notification_email` now always return string email addresses.
* `User.non_tj_email` now always returns either a string email address or `None`.
* Profile items (websites, phones, email addresses) are now displayed correctly.
Things that were intentionally not changed:
* Certain parts of the codebase, including parts that this PR modifies, hardcode references to `user.tj_email` that perhaps could (should?) be switched to `user.notification_email` were not. That is because the main goal of this PR is fixing bugs. A later PR can easily switch those to `user.notifcation_email`.
* The waitlist functionality (though it is disabled, this is worth mentioning) currently requires `user.primary_email` to be set. While perhaps that could be switched to …
=> Email and profile fixes/improvements

intranet/apps/auth/tests.py, intranet/apps/auth/views.py
Last night, #698 (which had a passing build) was merged at 11:53 PM. The Travis build failed. Specifically, `coverage run ./setup.py`, which was run shortly before midnight, failed.
This was due to a bug in the end-of-lunch eighth signup redirect code. Specifically, it hardcoded searching only for blocks that occurred today; it did not handle the cases when the block that had signups end in 20 minutes might be tomorrow.
Practically, this would never actually have occurred in production, but of course it is still a bug. This PR fixes it (as well as the test cases, which rely on the same incorrect assumption) and also takes the opportunity to refactor the code and offload more work onto the database.
=> Fix eighth signup redirect code and tests

intranet/templates/page_base.html
Per https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away and https://stackoverflow.com/questions/42250283/is-fastclick-js-still-needed, unless people are running old mobile browsers, fastclick is no longer needed.
Fixes #353
=> Remove fastclick

.travis.yml, Ion.egg-info/SOURCES.txt, Ion.egg-info/requires.txt, config/provision_vagrant.sh, docs/rtd-requirements.txt, docs/sourcedoc/intranet.apps.notifications.rst, docs/sourcedoc/intranet.rst, intranet/__init__.py, intranet/apps/announcements/notifications.py, intranet/apps/eighth/models.py, intranet/apps/eighth/notifications.py, intranet/apps/eighth/tests.py, intranet/apps/eighth/views/admin/maintenance.py, intranet/apps/events/notifications.py, intranet/apps/feedback/views.py, intranet/apps/notifications/tasks.py, intranet/celery.py, intranet/settings/__init__.py, requirements.txt, scripts/restart_celery.sh
Fixes #604. Makes #156, #709, and #710 possible.
Note that as it is currently set up, this will require `rabbitmq-server` to be installed on both development and production environments, and `scripts/restart_celery.sh` will need to be run 1) before starting the server and 2) any time a file used by Celery is modified (though for development environments, this isn't strictly necessary unless using features that have been offloaded to Celery).
=> Use Celery to send emails

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, fabfile.py, intranet/apps/bus/consumers.py, intranet/asgi.py, intranet/routing.py, intranet/settings/__init__.py, requirements.txt
Fixes #554 
This upgrades Ion from legacy Channels to the newest backwards-incompatible Django Channels 2.  The functionality for end users remains the same. This is also introduces our first hard requirements for Python 3.6+.
Edit: I have manually tested adding and removing buses as an admin and then viewing those buses as a regular user (all within my development environment).
=> Upgrade to Django Channels 2

intranet/apps/notifications/emails.py, intranet/settings/__init__.py
development. If necessary, developers can explicitly force sending the
email.
In most cases, developers only need to check that the correct email was
created which `msg` can do.
=> fix(notifications): refuse to send emails in

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.eighth.rst, intranet/apps/eighth/notifications.py, intranet/apps/eighth/tasks.py, intranet/apps/eighth/views/admin/activities.py, intranet/apps/eighth/views/admin/scheduling.py, intranet/apps/notifications/emails.py, intranet/apps/notifications/tasks.py, intranet/celery.py
The behavior described in #731 was expected and it's impossible to get messages logged from Celery to show up in Django logs, but this PR 1) makes our Celery tasks use Celery's logging system properly and 2) makes the Celery loggers respect `settings.LOG_LEVEL`.
So I guess this closes #731.
=> Celery logging fixes

intranet/static/css/login.scss, intranet/templates/auth/login.html
- Add "Reset password" link under login button
- Add "CSL Account Documentation" link in footer
- Add "CSL Account Documentation" link under the "Reset password" link when authentication fails
We currently have no links to the account documentation, and no links to the resetter site except from the account documentation. This PR makes those links very prominent.
=> Add "Reset password" and account documentation links

intranet/static/js/announcement.form.js, intranet/templates/announcements/approve.html, intranet/templates/announcements/request.html, intranet/templates/events/add_modify.html
- Block the text "ION" in announcements (closes #805)
* Also clean up some of the announcement templates as necessary to make this change possible
- Block the text "ION" in events (related to #805)
* Also clean up the edit/modify/request event template as necessary to make this change possible
As per #805:
> Users are beginning to more actively use "ION" to refer to Ion. This is incorrect.
=> Block use of ION in announcements and events

Ion.egg-info/SOURCES.txt, intranet/static/css/dark/eighth.signup.scss, intranet/static/img/Eighth-Icons-dark.svg
-  Change eighth signup block colors to create better contrast between signed up and not signed up blocks
- Use brighter activity icons in dark mode to increase contrast against background
In both cases, this increases contrast in places where there is low contrast.
=> Dark mode tweaks

intranet/apps/context_processors.py, intranet/settings/__init__.py, intranet/templates/oauth2_provider/authorize.html
- Add special message for users of the unofficial iOS app
People are complaining about the unofficial iOS app not working. We should head off these complaints by adding a specific message explaining that they should not use it.
=> Add special message for users of the unofficial iOS app

intranet/templates/oauth2_provider/base.html, intranet/utils/date.py
- Fix `get_date_range_this_year()` with December as turnover (partially fixes build)
- Add padding to the sides of OAuth provider base page so the text does not run up against it
The first commit partially fixes the build (see #829 for an explanation of the other bug breaking it), and the second one is a simple CSS tweak.
=> Miscellaneous fixes

.pylintrc, .travis.yml, intranet/apps/eighth/views/admin/groups.py, intranet/apps/eighth/views/admin/rooms.py, intranet/apps/eighth/views/admin/scheduling.py, intranet/apps/eighth/views/attendance.py
- Switch back to the latest version of Pylint (the bug described in #829 has been resolved)
- Disable Pylint's new `no-else-continue` warning
- Remove unnecessary list comprehensions
We should stay up-to-date with the latest version of Pylint
=> Update Pylint in Travis build

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.printing.rst, intranet/apps/printing/tests.py, intranet/apps/printing/views.py
- Add missing space
- Recommend users convert to a PDF if a file with a `.doc` or `.docx` extension can't be identified (has been tested in a development environment)
- Add a test to make sure the printing page renders correctly
Fixes a bug, adds a test (however minimal), and gives a helpful message to (likely) confused users.
=> Printing tweaks

intranet/templates/oauth2_provider/authorize.html
- Disables the "Dashboard" button when users try to authenticate to the iOS app so they can't use it just to pull up Ion quickly
- Recommends that users add Ion to their home screen instead
People should not use the unofficial iOS app just to open Ion quickly when we make it easy for them to do this another way.
=> Further discourage use of the iOS app

intranet/apps/sessionmgmt/views.py, intranet/static/css/sessionmgmt.scss
- Add bottom margin to device information "box"
- Fail more gracefully (no 404) if the user tries to revoke a session that has already been revoked
The "boxes" displaying information on each trusted device don't look good when squashed up against each other, and the 404 error is unexpected.
=> Session management tweaks

.flake8, .travis.yml, CONTRIBUTING.md, Ion.egg-info/SOURCES.txt, docs/developing/styleguide.rst, intranet/__init__.py, intranet/apps/sessionmgmt/views.py, intranet/apps/users/models.py, intranet/apps/users/tests.py, intranet/middleware/session_management.py, intranet/settings/__init__.py, pyproject.toml, scripts/format.sh
- Update `flake8`/`black` exclude lists
- Run `black`/`autopep8`/`isort` in Travis build
- Format everything with new `format.sh` script
@theo-o has been slowly blackifying the codebase. This makes it official and enforces it.
Note: `autopep8` is needed because on certain things `black` does not agree with `flake8`/`pylint`, so we have `autopep8` fix those.
=> Add formatting check to Travis build

intranet/settings/__init__.py
- Actually allow file uploads up to maximum set size
We have a 200MB limit set in the file upload validation code (and in production), but we do not actually set the Django setting that makes it accept larger files, so they error out.
=> Actually allow file uploads up to maximum set size

intranet/templates/signage/pages/bus.html
- Shrink bus route name even more when it overflows on signage
The route name is illegible in certain cases.
=> Shrink bus route name even more when it overflows on signage

intranet/static/js/bus.js, intranet/templates/bus/home.html
- Shrink bus route text if it's too large (not on signage)
See faa6a63 and #858.
=> fix(bus): shrink bus route text if it's too large (not on signage)

intranet/apps/context_processors.py, intranet/apps/users/models.py, intranet/static/css/base.scss, intranet/static/css/eighth.signup.scss, intranet/static/js/dashboard/common.js, intranet/templates/dashboard/dashboard.html, intranet/utils/helpers.py
- Unlock dark mode globally
- Add a "new feature" description to the dashboard mentioning dark mode and directing the user to the "Preferences" page to enable it
Dark mode has been tested and should be ready for school-wide deployment.
=> Unlock dark mode globally

intranet/static/css/eighth.admin.scss, intranet/static/css/responsive.scss
- Don't show horizontal scrollbars when resizing eighth admin page
The eighth admin page is able to adapt to a range of screen sizes, but
there are some size ranges where horizontal scrollbars are shown despite
having enough screen space to avoid this.
=> Don't show horizontal scrollbars when resizing eighth admin page

intranet/apps/api/views.py, intranet/apps/auth/signals.py, intranet/apps/files/views.py, intranet/apps/signage/pages.py, intranet/middleware/traceback.py
- Fix new Pylint unused argument warnings
Fixes the build.
Most of these cases need to match standard interfaces of some kind, so we have to just ignore the warnings.
=> Fix Pylint unused argument warnings

intranet/templates/schedule/calendar.html
- Remove duplicated JS includes in schedule calendar page
This fixes a bug where the dropdown in the nav does not work on the
calendar page. Essentially, we use a custom animation "easing" function
that's defined in jQuery UI, but the re-include of jQuery (core)
replaces the easing function list, removing that function.
Also, in general we shouldn't be including the same JS file twice.
=> Remove duplicated JS includes in schedule calendar page

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
- Require asgiref>=3.2.3
In production, we are experiencing [errors](https://sentry.tjhsst.edu/tjcsl/ion/issues/1984) (internal) that appear to be originating from `asgiref` following the `channels` upgrade over the weekend. Production has `asgiref` version `3.2.0` installed; upgrading to the latest micro release may fix this.
=> Require asgiref>=3.2.3

intranet/apps/eighth/views/signup.py, intranet/apps/users/models.py, intranet/apps/users/tests.py, intranet/static/js/eighth/signup.js, intranet/templates/eighth/multi_signup.html, intranet/templates/eighth/profile_signup.html, intranet/templates/eighth/signup.html, intranet/templates/nav.html
- Display exclamation mark icon on nav if there are any blocks within the next 3 days the user is not signed up for
- Show message about signing up earlier if a user signs up within 40 minutes of the signup deadline
- Show exclamation mark next to any blocks within the next 3 days the user is not signed up for
Closes #818
I have tested this locally, but given that it touches important parts of the signup code, additional testing should be performed.
See #818
=> Encourage students to sign up for eighth periods earlier

intranet/apps/auth/helpers.py, intranet/apps/auth/views.py, intranet/utils/helpers.py
- Improve login theme system
It is not easy to tell which login theme is active if changes need to be made other than including the CSS/JS files (such as with halloween mode, which needs dark mode to be enabled). This fixes that issue.
=> Improve login theme system

intranet/templates/eighth/signup.html
- Never display `fa-exclamation-mark` for blocks not today
Currently, signing up for a block that is more than three days in the future causes the `fa-exclamation-mark` icon to appear in the other block if the user is not signed up for that block. This change makes that impossible by simply not including the icon if the block is too far in the future.
=> Never display fa-exclamation-mark for blocks not today

intranet/apps/signage/models.py, intranet/templates/signage/base.html
- Use Page.order to sort signage pages
While attempting to deploy the eighth period signage page (added in 4f4c31599a549840666dc3798d4cc0adedfd46be) in production, I tried to set the `order` on the eighth page such that it would be placed above certain other pages. However, Ion did not recognize this option, preventing me from placing it correctly.
=> Use Page.order to sort signage pages

intranet/static/css/dashboard.scss
- Fix size of feature announcements on dashboard
Deploying #903 revealed a bug in the dashboard CSS: On wider screens, the feature announcement text is not restricted in width and stretches past the start of the widgets on the right. This fixes that bug.
=> Fix size of feature announcements on dashboard

intranet/static/js/dashboard/announcements.js
- Fix strange behavior of partially hidden announcements
If a "partially hidden" announcement is clicked to expand it and then clicked again (the body, not the title), it collapses and non-printable characters are added to the title. This behavior is unexpected, and this PR fixes it.
=> Fix strange behavior of partially hidden announcements

intranet/apps/eighth/models.py
- Fix log messages in `EighthSignup.objects.create_signup()` duplicate checks
- Ignore cache more aggressively in `EighthScheduledActivity.add_user()`
The log message bug was revealed in production, and the cache changes in 199c85373bfb0f44e700e00a0c917d7b5b8a2e38 have failed to prevent duplicate signups.
=> Eighth fixes/tweaks

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.middleware.rst, intranet/middleware/monitoring.py, intranet/settings/__init__.py
- Restrict access to Django Prometheus metrics
Non-superusers and hosts other than the `ALLOWED_METRIC_SCRAPE_IPS` do not need to see metrics.
=> Restrict access to Django Prometheus metrics

intranet/apps/eighth/views/monitoring.py
- Ignore cache in duplicate signup metric export
It seems to have been displaying inaccurate results due to caching.
=> Ignore cache in duplicate signup metric export

intranet/static/js/bus.js, intranet/templates/signage/pages/bus.html
- Fix font issues in bus display on signage
In production, the signage displays don't have Helvetica and Arial (the default fonts specified by SVG.js) installed. Instead, they fall back on the `sans-serif` default. Whatever this defaults to is a significantly different size from Helvetica and Arial, which results in behavior such as the route names overflowing the bus rectangles.
This change also allows adjusting the font size to something more legible.
=> Fix font issues in bus display on signage

intranet/routing.py
- Close incoming websocket connections that don't match a route
Should actually fix the `CancelledError`s mentioned in #891.
=> Close incoming websocket connections that don't match a route

intranet/templates/signage/base.html
- Force reload signage page at 1:30 AM
Signage pages sometimes experience difficulty connecting when they have just started up (they reboot at 1 AM), and sometimes static files are cached and changes do not propagate correctly. Reloading at 1:30 solves both these problems.
=> Force reload signage page at 1:30 AM

intranet/apps/announcements/models.py, intranet/templates/signage/pages/announcements.html, intranet/utils/html.py
- Remove links in announcements on signage server-side
JS link stripping does not appear to be fully functional.
=> Remove links in announcements on signage server-side

intranet/static/js/signage.js, intranet/utils/html.py
- Change href to `javascript:void(0)` instead of `#` on signage
It appears that an href of `#` targets the current page, which causes some weird bugs in signage's iframes.
=> Change href to `javascript:void(0)` instead of `#` on signage

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.emerg.rst, intranet/apps/emerg/tasks.py, intranet/apps/emerg/views.py, intranet/settings/__init__.py
- Check for "under maintenance" message in emergency info
- Update FCPS emergency info in a Celery task (closes #926)
- We should not show messages to the user if FCPS's website goes into maintenance mode.
- As explained in #926, the current strategy of updating emergency announcements in the views is suboptimal.
=> Emergency app updates

intranet/apps/eighth/views/attendance.py
- order eighth period blocks by block_letter in addition to date in take attendance view
- 
- 
The blocks for admins on the take attendance page are not properly ordered.
=> fix(eighth): order eighth period blocks by block_letter

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.utils.rst, intranet/apps/eighth/models.py, intranet/apps/eighth/views/signup.py, intranet/utils/locking.py
- Add generalized locking system (replaces case-speciifc system in cc257a57a977bae9e9a77876d26ece9ed94819f7)
- Lock on the user when toggling favorited activities
The locking code added in cc257a57a977bae9e9a77876d26ece9ed94819f7, if locking code was added elsewhere, could end up creating deadlock situations.
The `lock_on()` method added here attempts to avoid deadlocks by sorting the tables to lock on in a consistent way, ensuring that each thread would try to lock on the objects in the same order and avoiding deadlocks..
With regards to adding locking code to the favorited activities code, in production, there have been a lot of `IntegrityError`s emitted by this view when it tries to save and there's a duplicate object because of concurrent access. Since it already runs in a …
=> Locking changes

intranet/static/js/eighth/ui_init.js
- Setup selectize correctly on eighth admin pages
Recently, selectize inputs have not been showing up on some eighth admin pages. There is a chance that this is an unintentional side effect of #933, but I'm not sure.
=> Setup selectize correctly on eighth admin pages

intranet/static/js/dashboard/announcements.js, intranet/templates/announcements/view.html
- Don't partially hide announcements on announcement view page
If the user is only looking at one announcement, it should not be
collapsed.
=> Don't partially hide announcements on announcement view page

intranet/utils/locking.py
- Disable caching on all queries related to locking
In production, we still receive errors that would seem to suggest locking is not being performed properly. My current theory is that the queries are being cached and the "SELECT FOR UPDATE" query is not performed.
=> Disable caching on all queries related to locking

intranet/static/css/base.scss, intranet/templates/eighth/signup.html
- Add more prominent indicators of cancelled activities (closes #887)
- Ensure `<strong>` and `<em>` styles apply
- See #887
- Noticed while fixing #887; including in this PR since it is related (the "Cancelled" text is already supposed to be bold, but isn't because of this bug)
=> Add more prominent indicators of cancelled activities 

intranet/apps/announcements/models.py, intranet/apps/dashboard/views.py, intranet/apps/eighth/models.py, intranet/apps/eighth/serializers.py, intranet/apps/eighth/views/signup.py
- Improve `Announcement.announcementrequest` property -- reduce duplication and never reevaluate
- Prefetch `AnnouncmentRequest`s when listing announcements (they may be queried multiple times)
- Simplify `Announcement.is_visible_requester()` query (WARNING: changes behavior slightly)
- Reuse already-queried `EighthBlock` in signup view
- Don't query unneeded block/waitlist/scheduled activity information
- Fix type annotation
- Improve `EighthActivity.restricted_activities_available_to_user() `
- Fetch user information when listing announcements
See #958
=> Performance improvements

intranet/templates/error/static/501.html, intranet/templates/error/static/503.html, intranet/templates/error/static/504.html
- Update static error pages
The static error pages (used by Nginx in production) are inaccurate in some cases. This PR updates them to match the error templates and/or the correct HTTP status code meanings (for example, 504 means "Gateway Timeout," not "Internal Server Error").
=> Update static error pages

intranet/apps/announcements/models.py, intranet/apps/eighth/views/attendance.py, intranet/templates/eighth/signup_widget.html
- Avoid unnecessary query in eighth widget room list
- Don't unnecessarily query full hidden members lists
- Reorder visibility checks in `visible_to_user() `
See #958
=> Database query performance improvements

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.bus.rst, intranet/apps/bus/tasks.py, intranet/settings/__init__.py
- Reset bus routes in a Celery task
The cron job that resets bus routes is not currently being run in production. We should run it in a Celery task.
=> fix(bus): reset bus routes in a Celery task

intranet/static/css/dark/base.scss
- Fix appearance of some links in dark mode
The text-shadow makes it look blurred, and the light gray is inconsistent.
=> Fix appearance of some links in dark mode

intranet/apps/emerg/views.py, intranet/utils/html.py
- Fix links on FCPS emergency announcements
- Strip unsafe tags while we're at it
The latest FCPS emergency announcement about COVID-19 has a link to `/news/coronavirus-update` that is currently broken. Using `urljoin()` on link URLs fixes this.
This has been tested on a setup that is very similar to production.
=> refactor(emerg): fix links on FCPS emergency announcements

intranet/apps/auth/backends.py
- Use enum to indicate authentication result
- Clean up KRB5CCNAME deletion code
- Move kinit/pexpect code into a separate method
- `pexpect.spawnu()` -> `pexpect.spawn()`
- Pass Kerberos cache name on command line
The current Kerberos authentication code is very messy and has some potential race conditions.
This should be reviewed at least twice and heavily tested.
=> Improve Kerberos authentication code

docs/setup/postinstall.rst
In the paragraph starting with "You can then start...", these instructions tell the reader to login with the master password. However, this is before telling the reader is informed on how to create a user that they can log in with, creating ambiguity. This edit attempts to make it more clear what to do.
=> Remove ambiguity in Ion development environment initial setup instructions

docs/setup/vagrant.rst
Removed outdated and no longer necessary information about "ldap_simple_bind_password."
=> Remove obsolete information in the vagrant setup docs

.travis.yml, Ion.egg-info/SOURCES.txt, scripts/validate-commit-messages.py
- Validate commit message formats in CI
We should validate the formats of commit messages in CI to ensure all commit messages meet our standards.
=> Validate commit message formats in CI

.travis.yml, intranet/apps/eighth/models.py, intranet/apps/eighth/views/admin/attendance.py, intranet/apps/polls/models.py, intranet/utils/deletion.py
- Unpin pylint from 2.4.4 and fix build for 2.5.x
Once the upstream issues mentioned in #990 are resolved, we should switch back to the latest version of Pylint.
=> Unpin pylint from 2.4.4 and fix build for 2.5.x

intranet/apps/announcements/tests.py, intranet/apps/api/tests.py, intranet/apps/auth/views.py, intranet/apps/dashboard/views.py, intranet/apps/dataimport/management/commands/year_cleanup.py, intranet/apps/dataimport/tests.py, intranet/apps/eighth/tests.py, intranet/apps/eighth/views/activities.py, intranet/apps/emailfwd/tests.py, intranet/apps/parking/tests.py, intranet/apps/polls/views.py, intranet/apps/preferences/tests.py, intranet/apps/seniors/models.py, intranet/apps/seniors/views.py, intranet/apps/users/models.py, intranet/settings/__init__.py, intranet/templates/dashboard/seniors.html, intranet/templates/eighth/admin/start_of_year.html, intranet/utils/date.py
- Eliminate `settings.SENIOR_GRADUATION_YEAR` in favor of auto-detection based on current date.
Updating `settings.SENIOR_GRADUATION_YEAR` is annoying.
=> Eliminate settings.SENIOR_GRADUATION_YEAR

scripts/validate-commit-messages.py
- Add a check in the commit message validation script for non-lowercase first letter in commit message
- Adds comment explaining commit message validation script.
Some developers forget to abide by [our commit message format standards](https://github.com/tjcsl/ion/blob/master/docs/developing/howto.rst#formatting-commit-messages). This PR attempts to increase automation of testing of these standards.
=> Add check to commit message validation script

intranet/apps/polls/models.py
- Resolve bug where non-distinct polls can be returned from `Poll.visible_to_user()`
Currently, non-distinct querysets can be returned from this method.
=> fix(polls): use distinct polls in `Poll.visible_to_user()`

config/provision_vagrant.sh
- Use docker vagrant provisioner to setup redis layer instead of building from source
Building redis-server from source threw an error when building for me and docker is more reliable and faster than building from source.
=> fix: provision redis with docker instead of source

intranet/templates/dashboard/links.html
- Change the Mathematica link from https://guides.tjhsst.edu/math/mathematica to https://guides.tjhsst.edu/research/mathematica
https://guides.tjhsst.edu/math/mathematica 404s, it has been replaced by https://guides.tjhsst.edu/research/mathematica
=> fix(dashboard): fix broken Mathematica link

Vagrantfile, config/provision_vagrant.sh
- Upgrade vagrant box from `ubuntu/bionic64` to `generic/ubuntu2004`
- 
- 
Production uses postgres 12 which is available on ubuntu 20.04
Official Ubuntu image (`ubuntu/focal64`) takes a long time to boot compared to 
`generic/ubuntu2004`.
`generic/ubuntu2004` also supports a wider variety of Vagrant VM providers
=> fix(vagrant): upgrade box to generic/ubuntu2004

intranet/apps/eighth/serializers.py
- Partially revert ea97f5c0f4ac3b4d1fefb1da8dadc983a04159cc to restore `waitlist*` and `is_recommended`
- 
- 
ea97f5c0f4ac3b4d1fefb1da8dadc983a04159cc would cause some breakage with the JS
=> fix(eighth): partially revert ea97f5c0f4ac3b4d1fefb1da8dadc983a04159cc

intranet/templates/dashboard/seniors.html
- Fix graduation date added in template
This breaks the graduation countdown.
In #989, I preserved the previous value of the `senior_graduation` variable (a string representation of the graduation date) but for unknown reasons I also added the `date` filter here. The `date` filter tries to operate on this string, fails, and yields an empty string. The JS tries to parse this, fails, and displays bad information to the user.
=> fix(dashboard): fix graduation date added in template

intranet/static/js/bus-shared.js
Fixed rendering issues causes by `hidden` elements only being present in signage.
=> fix(bus): fix js display error

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.dataimport.management.commands.rst, intranet/apps/dataimport/management/commands/delete_users.py, intranet/apps/dataimport/tests.py
- Add the `delete_users` management command
To allow us to mass remove users from Ion with their FCPS student IDs, for instance, when they have withdrawn.
I will squash all commits before merging.
=> feat(dataimport): add delete_users management command

intranet/templates/auth/about.html, intranet/templates/welcome/base.html
- Replace the links pointing to https://livedoc.tjhsst.edu with archive.org links or links to documentation.tjhsst.edu.
Livedoc has been deprecated and taken down. Therefore, these links don't work anymore.
I'm not sure if I should replace the attribution link with an archive.org link or if we should add something to documentation.tjhsst.edu and link to that instead.
=> fix(templates): fix broken Livedoc links

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.dataimport.management.commands.rst, intranet/apps/dataimport/management/commands/import_staff.py, intranet/apps/dataimport/management/commands/import_students.py, intranet/apps/dataimport/tests.py
- Add commands to import students (`import_students`) and staff (`import_staff`)
We don't have a command to bulk import students and staff from CSVs, or at least as far as I'm aware. And we need one soon for new staff/students.
=> feat(dataimport): add import_students and import_staff command

intranet/apps/announcements/views.py, intranet/apps/events/views.py
closes #660 and #661
- Log admin usernames and timestamps for actions in `events` and `announcements`.
- Logger messages formatted as: `Admin test_admin added event: Assembly (event id)`.
- To more easily trace the modifications done to events and announcements by admins (see #660, #661)
=> feat(events): record admin actions over events and announcements

intranet/templates/docs/accounts.html
- add FAQ on when accounts are created for incoming students
- remove FAQ on account transition
- 
We need to add information to preempt questions from incoming students.
=> docs: add FAQ on accounts for incoming students

intranet/apps/dashboard/views.py, intranet/settings/__init__.py, intranet/templates/dashboard/dashboard.html
Currently, unless commented manually, the senior forwarding message on
the dashboard is rendered for all seniors, regardless of when it is
during the school year. We intend for the message to be only rendered
near the end of academic year.
This commit restricts the rendering of this message to
settings.NEAR_GRADUATION_DAYS (50).
- Restrict rendering of senior forwarding message to seniors NEAR_GRADUATION_DAYS out from graduation
- 
- 
The current code displays the message at all points during senior year.
NOTE: This has not been tested
=> fix(dashboard): limit time when senior graduation message is shown

intranet/apps/eighth/serializers.py
- Add the `finance` and `comments` field to `intranet/apps/eighth/serializers.py`
Without this fix (or a workaround), one cannot select an eighth activity on the signups view - the following error shows in the dev console.
Fixing a bug introduced in 297746388a856081f6821ac2e6f9edca112b4bc7 and ea97f5c0f4ac3b4d1fefb1da8dadc983a04159cc.
=> fix(eighth): add finance and comments field

intranet/templates/eighth/take_attendance.html
- Change `outerText` to `innerText` in JavaScript
- Apparently `outerText` is Chrome specific. I've now tested `innerText` in Chrome, Firefox, Edge, Safari and Opera. I also can't find any incompatibility reports in other browsers.
=> fix(eighth): fix bbcu-link for firefox browser

intranet/templates/docs/accounts.html
-  Update CSL Account Documentation to reflect changes for SY2020-21 and clarify some vocab and steps.
- 
- 
Some parts of the current accounts docs are unclear.
=> fix(docs): update accounts documentation to clarify aspects

intranet/apps/eighth/views/admin/blocks.py
closes #1042
- Remove `order_by`
- The behavior of `order_by` causes duplicate blocks. The desired sorting seems to already be achieved by `sorted()` in the line below.
=> fix(eighth): remove duplicate results in printed roster

Ion.egg-info/SOURCES.txt, intranet/apps/auth/tests.py, intranet/apps/auth/views.py, intranet/apps/eighth/urls.py, intranet/apps/eighth/views/signup.py, intranet/settings/__init__.py, intranet/static/css/eighth.schedule.scss, intranet/templates/eighth/location.html
- redirect to `/eighth/activity/location` starting 20 minutes before the first 8th block of a day and ending 20 minutes after that block's start time.
- `/eighth/activity/location` details the two upcoming 8th blocks, including title, location, sponsors, comments and descriptions
- avoid loading `/` or `/eighth` for students checking 8th period codes during peak times
=> feat(eighth): redirect to info page near eighth period

intranet/apps/auth/views.py
Basically changes the show time for `eighth_location` from within 20 minutes of the first block start time to 30 minutes before first block start through 20 minutes after last block start.
Forgot to PR this last week, sorry.
=> fix(eighth): change times for eighth_location to be shown

intranet/apps/eighth/views/profile.py
- Remove `user.properties.birthday` from `edit_profile_view`
`user.properties.birthday` was removed earlier (a378eeca9858d98de47d6711b73190952b302ef1); this form is causing a 500 in production:
AttributeError: 'UserProperties' object has no attribute 'birthday'
=> fix(eighth): remove birthday fields from profile edit page

scripts/get_ldif.py
- Add a student's TJ email, or a staff's FCPS email, to the LDIF generated by `gen_ldif.py`
For reasons which were put in MM, LDAP should hold students' or staff members' emails.
=> feat(scripts): add TJ email to LDIF

intranet/templates/error/500.html, intranet/templates/error/503.html, intranet/templates/error/static/500.html, intranet/templates/error/static/501.html, intranet/templates/error/static/502.html, intranet/templates/error/static/503.html, intranet/templates/error/static/504.html
- Add a link to the CSL status page ([status.tjhsst.edu](https://status.tjhsst.edu)) on the 5xx error pages.
- Fix some formatting/HTML on those pages.
The status page is probably a good idea to link to on these pages.
=> chore(error): add status page link to error pages

intranet/apps/polls/views.py, intranet/templates/polls/results.html
- Change gender display from a back end option to a front end one
- Make the gender option actually work 
Previously there was an GET option `no_gender` that was supposed to display the poll results without the gender counts. However, the columns were still there, it looked cluttered and had IMO unnecessary information. Now, gender stats are always calculated and javascript is used to toggle the tables based on what you want to see.
=> fix(polls): change how polls display gender

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.dashboard.rst, intranet/apps/announcements/tests.py, intranet/apps/bus/tests.py, intranet/apps/dashboard/tests.py, intranet/apps/dataimport/tests.py, intranet/apps/eighth/tests.py
Adds unit tests for:
- `intranet.apps.eighth.management.commands.update_counselors`, a command to update students' counselors
- `intranet.apps.dataimport.management.commands.delete_users`, a command to delete users
- [`intranet.apps.bus.views.home`](https://github.com/tjcsl/ion/blob/master/intranet/apps/bus/views.py#L13), to test both `morning` and `afternoon` views no matter the time of day when these tests are ran
- `intranet.apps.dashboard.views.gen_schedule` and `intranet.apps.dashboard.views.gen_sponsor_schedule`
- Views to generate statistics for `EighthActivity`es (`intranet.apps.eighth.views.activities`).
Self explanatory.
=> test: update_counselors, delete_users, bus view, gen_schedule, EighthActivity statistics

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.emerg.rst, docs/sourcedoc/intranet.apps.itemreg.rst, docs/sourcedoc/intranet.apps.lostfound.rst, intranet/apps/emailfwd/tests.py, intranet/apps/emerg/tests.py, intranet/apps/events/tests.py, intranet/apps/itemreg/tests.py, intranet/apps/lostfound/tests.py, intranet/apps/lostfound/views.py, intranet/templates/events/add_modify.html
- Adds unit tests for these apps
- `emailfwd`
- `lostfound`
- `itemreg`
- Cosmetic changes
- Event request app
- fix showing the header when requesting events
- Change "submit query" text to something a little more user friendly
=> Add unit tests for emailfwd, lostfound, itemreg apps; cosmetic changes

intranet/apps/eighth/Hybrid-README.rst, intranet/apps/eighth/views/admin/blocks.py
- Create a fourth group to handle those always in-person
Although block creation works fine as is, the few people who are in both `in-person (a-k)` and `in-person (l-z)` get put in both Virtual and In-Person blocks when 8PO goes to sticky into something like SEL. I already made the group changes in production.
=> fix(eighth): handle students always in-person better

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.search.rst, docs/sourcedoc/intranet.apps.seniors.rst, docs/sourcedoc/intranet.apps.signage.rst, intranet/apps/error/tests.py, intranet/apps/search/tests.py, intranet/apps/seniors/tests.py, intranet/apps/sessionmgmt/tests.py, intranet/apps/signage/tests.py, intranet/apps/signage/views.py, intranet/test/ion_test.py
- Add unit tests for these apps
- `seniors`
- `search`
- `error`
- `sessionmgmt`
- `signage`
- Add docstrings/typing hints to `ion_test.py` and `intranet.apps.signage.views`
=> Add tests for seniors, search, error, sessionmgmt, signage apps, docstrings/typing hints

intranet/templates/events/event.html
The edit button doesn't actually show up because context passes `is_events_admin` and this was looking for `events_admin`.
=> fix(events): fix home template

intranet/static/css/page_base.scss, intranet/templates/eighth/take_attendance.html
Fixes #1048
Supersedes #1107
Fix the "disappearing name" on the take attendance view
The issue, I believe, is with [this line](https://github.com/tjcsl/ion/blob/master/intranet/static/css/responsive.core.scss#L183); it is hiding anything with the class `user-name`. The user dropdown menu in the top right has shows your name with the class `user-name`. But, the table also uses the class `user-name` for the names of users, and thus those names disappear too.
Self explanatory
=> fix(eighth): fix disappearing name on take attendance view

intranet/static/css/dashboard.widgets.scss
After attendance is taken, these classes cause the widget to render incorrectly in hybrid mode.
=> fix(hybrid): fix eighth sponsor widget

intranet/apps/eighth/views/signup.py
Basically, when a student loads the eighth period signup page, and when hybrid Ion is enabled but there are no future blocks, `future_block[0]` results in an `IndexError`, and the eighth period signup page doesn't load. This commit/PR fixes that.
=> fix(hybrid): fix future_block out of range error

intranet/templates/special/hoco_ribbon.html
- Removes the `https://` prefix and the trailing slash from the URL to `homecoming.tjhsst.edu` in the homecoming "ribbon", as shown below
It looks better
=> fix(templates): clean up hoco ribbon

intranet/apps/eighth/forms/admin/scheduling.py, intranet/apps/files/views.py, intranet/apps/users/models.py
- Replace backslashes with forward slashes in `title`, `comments` and `admin_comments` fields.
- Make minor formatting changes to align with new pylint standards
This issue was reported by 8PO. Essentially, JSON does a really bad job of handling backslashes with any sort of variability in format. There is no case in entering titles or comments where a backslash is needed -- forward slashes work just as well -- so we can just replace the backslashes.
For pylint, it was complaining about not using `with` to open files in `files.views` and not using `min()` in users.models.
=> Character rendering + Pylint fix

intranet/apps/eighth/views/admin/rooms.py
When using the Room Utilization function in the Eighth Admin dashboard, the logic filters out all room associated with an activity, not just those in use on that particular day. For instance, if Sysadmins was usually held in Room 1 and the Sysadmins `EighthActivity` had Room 1 listed, but then the activity had been overridden to happen in Room 2 at the `ScheduledEighthActivity` level, Room 1 wouldn't show up as open.
=> fix(eighth): use get_true_rooms when filtering

Vagrantfile
This has been repeatedly mentioned and no one got around to doing it. As far as I can tell, the VirtualBox GUI serves no purpose for the Ion development environment, so it seems best to just get rid of it.
=> fix(vagrant): remove unnecessary VirtualBox GUI

intranet/templates/dashboard/links.html
closes #608
Because the current categories do not make sense and we don't need a link to blackboard anymore.
=> chore(dashboard): refresh links

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, intranet/apps/auth/__init__.py, intranet/routing.py, pytest.ini, requirements.txt
`django-prometheus`, `django-cacheops`, `django-debug-toolbar` and `django-oauth-toolkit` haven't updated to remove some depreciation, but that doesn't actually become an issue until django 4. Because of this however, we have to mute the depreciation warnings in pytest.
I went over the changelogs pretty thoroughly and I'd like to put this in this weekend, after deploying it to `ion-dev`, but please see if I've missed anything.
E: to be clear, still very much testing this
=> build(deps): update to django3

intranet/apps/events/tasks.py
python3 throws a weird syntax error when using a list over a tuple and excluding the `as e`, so I fixed that.
=> fix(events): catch all errors

intranet/templates/oauth2_provider/application_form.html
We should keep these docs in `guides` which gets updated much more frequently and is the official centralized place for all of our user facing docs.
=> docs(oauth): update oauth docs location

intranet/apps/auth/views.py, intranet/apps/welcome/tests.py
- When you log into Ion as part of authorizing an oauth application, you are redirected away from the oauth by the welcome page. This is undesired and annoying.
=> fix(welcome): don't redirect oauth requests to welcome

Ion.egg-info/SOURCES.txt, intranet/static/js/events.js, intranet/templates/dashboard/dashboard.html, intranet/templates/events/event.html, intranet/templates/events/home.html
- Makes the attend/don't attend event button work.
- The attend button is not part of the attend event form, but is a separate `a` element, which is why it does not work.
- Uses JavaScript to submit the attend form when the attend button is clicked, fixing the issue. 
- Also makes the attend button show up on the dashboard.
- Currently, the attend event button doesn't do anything when clicked.
- See, for example, https://ion.tjhsst.edu/events/784
- The button also doesn't currently show up on the dashboard. Allowing people to mark as attending from the announcement post increases visibility.
- In the future, might want to look into making the attend button `<input type="submit">` to eliminate need for JS. However, this could create formatting issues which is why I chose to keep it where …
=> fix(events): make attend function work

intranet/apps/events/views.py, intranet/templates/dashboard/dashboard.html, intranet/templates/events/event.html, intranet/templates/events/home.html, intranet/templates/events/month.html, intranet/templates/events/week.html
- Shows the full date & time and events calendar icon if the event is shown on the dashboard. 
- Adds events in the "special" section to calendar (events that have the option checked for show attending, scheduled activity, announcement or show on dashboard). Not previously implemented due to styling issues. 
- If the event is shown on the dashboard, it should include which day the event is on instead of only the time (on the calendar view, it only shows time). 
- Icon is shown to match formatting on dashboard and hidden in calendar to save space.
=> fix(events): integration with dashboard, special event display

intranet/apps/events/tests.py, intranet/apps/events/views.py, intranet/static/css/events.scss, intranet/templates/events/event.html, intranet/templates/events/home.html, intranet/templates/events/join_event.html, intranet/templates/events/roster.html
- The show_all button is currently visible for all users, but only works for admins. Takes out the show_all button for non-admins. 
- More mobile-friendly format for events; the text is currently overlapping.
- Import JS to make attend button work on roster view. 
- Small content changes: remove "View Roster" button from the view roster page, remove redundant "no events" text.
=> fix(events): show_all fix, mobile-friendly format

intranet/templates/search/search_results.html
The search results should display all graduates as graduates and not "Grade 1X"
=> style(search): change all alumni to graduate in search results

intranet/apps/events/models.py, intranet/apps/events/views.py, intranet/static/css/events.scss, intranet/static/js/events.js, intranet/templates/events/event.html, intranet/templates/events/home.html, intranet/templates/events/month.html, intranet/templates/events/week.html
Mobile friendly calendar: 
- For week view, days are shown vertically
- For month view, table has a scrolling overflow
- Page width fills the screen
- Disables the sidebar from appearing each time you swipe left when in month view
- Calendar was hard to navigate on mobile devices
Builds off the previous events fix, PR #1315 .
=> feat(events): responsive mobile calendar

intranet/static/css/schedule.scss, intranet/static/js/schedule.js, intranet/templates/schedule/calendar.html, intranet/templates/schedule/month.html, intranet/templates/schedule/week.html
Mobile friendly calendar: 
- For week view, days are shown vertically
- For month view, table has a scrolling overflow
- Page width fills the screen
- Disables the sidebar from appearing each time you swipe left when in month view
Also adds borders in the month view for desktop and mobile
- Calendar was hard to navigate on mobile devices
=> feat(schedule): responsive mobile calendar

config/docker/docker-compose.yml
- Makes Git trust the root Ion directory for all containers.
- The Docker daemon needs root privileges, requiring the use of `sudo` or adding the user to the `docker` group. 
- When running Docker as `sudo` and the directory containing Ion's source code is owned by another user, Git will not run because the directory is not trusted.
=> fix(dev): running docker as sudo

intranet/templates/eighth/signup.html
Non eighth admins are unable to see an 8th-period roster due to privacy issues, and the button is redundant, and users clicking it at scale creates unnecessary requests.
Hide button for non-admins
=> style(eighth): remove roster button for non-admins

intranet/apps/context_processors.py, intranet/apps/schedule/urls.py, intranet/templates/nav.html, intranet/templates/schedule/admin_home.html, intranet/templates/schedule/calendar.html
- Add schedule calendar to left navbar
- Change `/schedule` to go to the schedule calendar (used to go to the admin interface)
- Schedule is accessed a lot, adding to navbar makes it easier to locate
- The new URL syntax is more in line with other apps
=> refactor(schedule): add schedule to nav, change urls

config/docker/Dockerfile
- Use npm sass instead of the now-deprecated rubygems sass
Rubygems sass breaks on workstations/FCPS wifi, and is deprecated
=> fix(dev): change ruby sass to npm sass to fix deprecation

intranet/apps/signage/pages.py, intranet/apps/signage/views.py, intranet/settings/__init__.py
- Create school start and end time field to centralize spaced-out references to dismissal time.
- Automatically update start and end time for summer school.
- Automatically update year for each school year (but `settings` should still be manually updated each year).
- Migrate fields from `ion-app`'s `secret.py`.
- Update school, hoco start/end, graduation dates for the coming school year.
- Generally good practice to have one place to put start and end time
- Non-secret values should go here
=> feat(settings): add school start/end times, summer school, update dates

intranet/apps/dashboard/views.py, intranet/settings/__init__.py
- Redirect to the bus page when loading dashboard near dismissal (3:55 - 4:20, time adjusted of course based on `settings` variables).
- Virtually all requests to Ion near dismissal are to `bus`, `index`, or `login`. Number of requests to `index` and `bus` are nearly equal, suggesting people are just loading the dashboard and then going to the bus app. Source: Grafana.
- Better performance
=> feat(dashboard): redirect to bus page near dismissal

intranet/apps/eighth/tests/test_signup.py
- Change `test_signup` to use `timedelta` 
- Tests fail between 11:00 and 11:59 pm because adding 1 to `now.time().hour` would have hour as 24
=> test(eighth): fix tests failing between 11-11:59pm

intranet/templates/eighth/signup.html
- Hides sign up button on restricted activities the user is not authorized to sign up for
- Hides view roster button when signed up for activity (#1385 only hid button when not signed up)
- Streamline UI (sign up button is hidden on full activities, so should also be hidden for restricted)
=> style(eighth): hide signup button for restricted activities

intranet/static/css/dark/polls.scss, intranet/static/js/polls-vote.js
- Apply styling for dark mode in ranked choice voting
- Fix small bug where a pipe symbol ( | ) isn't converted to a dash ( - ) if the choice isn't a link
=> refactor(polls): style ranked choice for dark mode

intranet/templates/oauth2_provider/application_detail.html, intranet/templates/oauth2_provider/application_form.html
Add explicit help text showing that the client's secret is hashed and hide it after it's made.
=> style(cslapps): added client secret warning for oauth

intranet/static/css/dark/bus.scss, intranet/templates/bus/home.html, intranet/templates/bus/morning.html
- Change bus status text to improve visibility in dark mode
- (Partially) resolves #1453 
It is hard to read to the bus message when on dark mode
=> fix(bus): make bus status indicators visible in dark mode

intranet/apps/signage/views.py, intranet/static/css/hoco_ribbon.scss, intranet/templates/signage/base.html, intranet/templates/special/hoco_ribbon.html
- Adds homecoming scores (currently only on login page) to Ion dashboard and Signage homepage
- Resolves #1412 
It is somewhat inconvenient to have to visit [the homecoming site](https://homecoming.tjhsst.edu) or log out from Ion in order to view hoco scores
=> feat(hoco): add hoco scores to Ion dashboard and signage homepage

intranet/static/css/signage.base.scss
- Move TJ logo further down on vertical signages
- Fix hoco scores added in #1454 from overlapping with the TJ logo on vertical signages
- Fixes a bug
- Looks better
=> fix(hoco): move TJ logo down on vertical signages

intranet/apps/emerg/views.py, intranet/static/css/dashboard.scss, intranet/static/css/emerg.scss, intranet/utils/helpers.py, intranet/utils/html.py
- Fix FCPS emergency status text not displaying (the title will display, but the body text won't)
- Allow dispaying multiple lines from the CSL status page - currently only one line of a status announcement will be shown
- A few styling changes, adds link to FCPS/CSL status page in title of status announcement
=> refactor(emerg): styling + fix FCPS status, CSL linebreaks breaking

intranet/static/css/page_base.scss, intranet/static/css/responsive.core.scss, intranet/static/js/common.header.js
- Moves the eighth absences icon to the left of the header navbar on mobile
- #1379 introduced an apps icon to the navbar which would (if enabled) overlap with the absence icon
=> style(nav): move absent icon to left on mobile

intranet/templates/announcements/approve.html
Message used to say that the teacher submitted the announcement, when it should say the student.
For example, assume Bob requests an announcement for Mr. Joe to approve. The message currently reads:
"Mr. Joe submitted an Intranet announcement, and has asked for you to approve its posting."
It should read:
"Bob submitted an Intranet announcement, and has asked for you to approve its posting."
=> fix(announcements): fix teacher approval message

intranet/static/css/dark/bus.scss
Color was previously grey, making it hard to see on the red warning background.
=> refactor(bus): adjust warning text color for dark mode

intranet/apps/users/models.py, intranet/templates/nav.html
- Add function "should_see_polls" for User model
- Use it in a template tag in nav.html 
The function should_see_polls returns true if there are any active polls visible to the user or if the user has admin permissions to polls in which case the polls icon should always be available. This function is used in a template tag in nav.html to only show the polls icon when necessary for the user.
=> feat(polls): fix poll visibility

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
- Fix `django-formtools` breaking `/eighth` for teachers
- Rollback to v2.3 after bump in https://github.com/tjcsl/ion/commit/e732f3bb27148068297ce8d56b93178db7ce85a2
=> Fix formtools

SETUP.md
- Update SETUP.md to contain correct information about vagrant and virtualbox
- Information under vagrant and virtualbox is incorrect (Likely copy and pasted from under docker section)
- Links also do not work and point to the wrong page
=> fix(docs): fix virtualbox and vagrant docs

intranet/apps/auth/backends.py, intranet/apps/auth/forms.py, intranet/settings/__init__.py
- Removes the `LOCAL.TJHSST.EDU` realm from auth
- `LOCAL` is no longer used.
- If Kerberos authentication for the `CSL.TJHSST.EDU` realm fails, `LOCAL` is checked. However, since `LOCAL` doesn't exist, the request just hangs until the timeout (currently 15 sec, lowered to 10 sec in this PR) stops it. This is what is causing the really slow login for wrong passwords.
- This lowers the incorrect login loading time from around 20 seconds to 3 seconds.
Please monitor carefully when deploying! I tested this on dev but if anything breaks due to production's config, even though it's highly unlikely, we should be ready to revert.
=> perf(auth): remove LOCAL

config/docker/Dockerfile, config/docker/docker-compose.yml, intranet/settings/__init__.py
- pipenv isn't needed to run celery and celerybeat
- Also small change to allow `.local` in ALLOWED_HOSTS
=> fix(dev): remove unneeded pipenv commands

intranet/apps/auth/views.py
- Removes the `@login_required` decorator for reset_password_view, because it blocks expired password resets
- Adds a `sensitive_post_parameters` decorator for the old and new password POST parameters, as is also done in index_view
When a user's account has an expired password and the user cannot perform a regular log-in, a return value of `KerberosAuthenticationResult.EXPIRED` is given from `KerberosAuthenticationBackend`. The login form returns the `RESET_PASSWORD` service user, but does not log in to it before redirecting to the reset_password route.
However, the reset password page is locked behind requiring authentication. Since `login()` wasn't called on the returned user from the authentication form, the user is then redirected back to the login page, preventing them from logging …
=> Remove @login_required decorator for reset_password_view

intranet/apps/dashboard/views.py
There has been an increasing amount
of announcements posted to Ion,
so increasing the number visible
at a time will help with navigating
all of them.
- 
- 
-
=> refactor(dashboard): increase number of announcements displayed to 15

intranet/templates/dashboard/links.html
- Remove `Contact an Ion Agent` link that was added for the 2023 homecoming scavenger hunt
=> chore(misc): cleanup scav hunt link

intranet/apps/events/admin.py
- Change `Event.scheduled_activity` and `Event.announcement` fields to raw_id in Django Admin
Having these fields (especially `scheduled_activity`) as normal dropdowns causes a page load timeout, since Django Admin queries for every row in their respective models when creating or editing events.
=> fix(events): fix events admin load timeout

intranet/apps/printing/views.py
- Only add printers to Ion's printer list if the `lpstat` command output does not indicate they're disabled 
It is often helpful to hide printers from Ion by just disabling them in CUPS, as opposed to deleting them entirely
=> feat(printing): hide printers which are disabled on CUPS

intranet/apps/printing/views.py
- Make sure a printer's name (referred to as description) is not overridden by other printers
Fixes a bug that affects #1603
=> fix(printing): fix disabled printers bug

config/docker/Dockerfile
- Specify version of alpine instead of using latest
- Fix error where `ERROR: unable to select packages: kinit (no such package): required by: world[kinit]`
- New alpine docker image has a fix to make it work but in the future it is better to specify a static version in case new versions break.
=> fix(dev): fix docker env breaking on latest alpine version

README.rst
- Changed from https://www.tjhsst.edu to https://tjhsst.fcps.edu
Old url gave a redirect notice
=> docs: Fix outdated README.rst hyperlink

.github/CODEOWNERS
- Make @tjcsl/intranet-admins the sole code owner
GitHub Teams now support auto-assigning members for review. So, making the team code owner is simpler/more convenient.
This replaces #1634.
=> chore(docs): simplify CODEOWNERS

config/docker/entrypoint.sh
- Set the `PYTHONUNBUFFERED` environment variable in `entrypoint.sh`
Previously, print statements without `flush=True` would not be displayed until a server restart. This change unbuffers `stdout` and `stderr` from Django's development server to allow for easier debugging with print statements.
=> fix(dev): don't buffer Django output

intranet/static/css/welcome.scss
- Don't apply `margin-left: 8px;` to the dashboard icon
- Consolidate some scss
The dashboard icon is too far right due to a CSS property that adds margins to the left of icons. This property was intended for icons placed to the right of text, and therefore should not apply here.
Before and after:
=> style(welcome): center the dashboard icon

config/docker/Dockerfile
- Use `python:3.8.19-alpine3.18` as the base image
- Don't install Python 3.11
Python 3.8 better emulates production Ion at the moment, and this change can help catch bugs like 9afc0466a186016bc9f13e9534bb6205381840a1 before they hit production.
=> fix(dev): use python 3.8

intranet/apps/eighth/models.py, intranet/apps/eighth/tests/test_signup.py, intranet/templates/eighth/activity.html, intranet/templates/eighth/admin/schedule_activity.html, intranet/templates/eighth/multi_signup.html, intranet/templates/eighth/profile_signup.html, intranet/templates/signage/pages/eighth.html
Closes #1577
- Replaced all 48 hour presign text instances in Ion with the 2 day text 
- Consistency in text across the codebase
=> chore(eighth): replace text instances of 48 hour presign with 2 day

config/docker/docker-compose.yml
- Use the service name (`django`) instead of the container name (`intranet_django`) in `depends_on` attributes
Before:
```
service "celery" depends on undefined service "intranet_django": invalid compose project
```
After:
```
[+] Building 0.3s (11/11) FINISHED
```
This bug was introduced in f041203106924e162483a570b8d5c450026253be (PR #1658).
=> Fix depends_on attributes in docker compose

scripts/validate-commit-messages.py
The conventional commit grammar allows the scope to be any utf-8 characters, except for newlines and parenthesis (see [here](https://github.com/conventional-commits/parser#the-grammar)).
Currently, we only accept the lowercase English alphabet.
=> fix(scripts): fix scope regex to match convention commit specification

intranet/apps/announcements/views.py, intranet/apps/search/views.py
- Stop restricted announcements from being found via search and seen via announcement permalink if it is not supposed to be seen by the user
- Announcements that are not visible to a user's group on the home page are still visible via permalink and search. The suggested changes will make the visibility restrictions consistent across the board so users do not see an announcement they are restricted from
=> fix: enforce announcement visibility restrictions (closes tjcsl#1677)

Ion.egg-info/PKG-INFO, Ion.egg-info/requires.txt, intranet/apps/auth/backends.py, intranet/apps/auth/helpers.py, intranet/apps/auth/tests.py, intranet/settings/__init__.py, requirements.txt
- Simpler than the somewhat hacky Kerberos implementation
- Respects PAM and SSSD settings
- Useful when Kerberos is down (like earlier today) because SSSD cache will be used
=> feat(auth): switch to PAM

intranet/apps/eighth/views/admin/groups.py, intranet/apps/eighth/views/attendance.py, intranet/apps/users/views.py, intranet/utils/deletion.py
- Declare variables as `None` in the problematic functions at the start, and assume they will be set later on so pylint doesn't complain
This makes linting checks pass (I think)
=> chore: changes to let lint checks pass

intranet/static/js/eighth/statistics.js
- Make stats correct based on actual eighth period dates
- current stats are wrong
- See activity 3261
- dates should be given within the data object in Chart.js, otherwise it goes chronologically. If num data entries is less than labels then it won't fill properly, although even if they are the same length the content is still wrong.
=> fix(eighth): correct stats dates

intranet/templates/signage/pages/bus.html
- Change `padding `and `left` dynamically if `sign.landscape` is not true
Prevents the containers from overlapping with the bus spots
before:
after:
=> fix(signage): fix text containers overlapping bus spots in portrait mode (closes tjcsl#1680)

intranet/apps/printing/views.py, intranet/apps/users/models.py, intranet/settings/__init__.py, intranet/templates/nav.html, intranet/templates/printing/print_form.html
- Add a rate limit of 10 POST requests per minute to ion printing
- Fix some linting errors from previous contributors in the printing/views.py file so checks can pass
Blocks excessive printing by users to prevent abuse or overload of the printers
=> feat(printing): add rate limit to print job requests (closes tjcsl#662)

.github/workflows/ci.yml, ci/spec.yml
Hopefully this fixes the CI.
I couldn't add the link to the fix in the commit description (`validate-commit messages` line-too-long >:()
so I'll add it here:
https://github.com/actions/runner-images/issues/6486#issuecomment-1294714467
(credit to Krishnan for finding it)
=> fix(ci): update mirrors before installing

intranet/apps/printing/views.py
- replace all instances of `PRINTING_PAGES_LIMIT` with `PRINTING_PAGES_LIMIT_STUDENTS` and `PRINTING_PAGES_LIMIT_TEACHERS` and logic where appropriate
This will fix the attribute error when requesting a print job (i accidentally used the old version of this code when I was resolving the merge conflicts for the original PR #1666 )
=> fix(printing): attribute error when requesting print job

requirements-dev.txt
[importlib_metadata](https://importlib-metadata.readthedocs.io/en/latest/history.html) v8.5.0 (released 9/11/24) throws a `TypeError unhashable type: 'types.SimpleNamespace'` when running the app ([see](https://stackoverflow.com/questions/78977665/django-autoreload-raises-typeerror-unhashable-type-types-simplenamespace)). This PR downgrades `importlib_metadata` to v8.4.0.
=> fix: unhashable type error with importlib_metadata

config/docker/entrypoint.sh
- Let Django handle `SIGTERM` signals in the docker env
DB's are stateful, so it's important to let them clean up after themselves when killing a docker compose session. This way, django can control how to peacefully shutdown connections to the DB.
It also has the added benefit of decreasing shutdown times from **10.2s to 0.5s**.
=> fix: let django handle SIGTERM

intranet/apps/dataimport/management/commands/import_photos.py
- importing teacher photos should only consider staff users
- It would be awfully unfortunate if a teacher and a student both had the same names and the wrong image was loaded
=> fix(misc): import teacher photos should only find staff

intranet/static/css/bus.scss, intranet/static/css/dashboard.scss, intranet/static/css/dashboard.widgets.scss, intranet/static/css/events.scss, intranet/static/css/page_base.scss, intranet/static/css/printing.scss, intranet/static/css/responsive.core.scss, intranet/static/css/responsive.scss, intranet/static/css/schedule.scss, intranet/static/css/welcome.scss, intranet/static/themes/halloween/halloween.css, intranet/templates/dashboard/dashboard.html, intranet/templates/enrichment/home.html, intranet/templates/events/home.html, intranet/templates/events/month.html, intranet/templates/nav.html, intranet/templates/page_with_header.html, intranet/templates/welcome/base.html
The following changes make Ion more responsive across all devices and improve the UX. Most changes are given a before and after image to hopefully make reviewing this PR easier, but very minor changes don't.
`dashboard.scss`
- Removed unnecessary left padding on all h2 tags which made some titles look strange ([before](https://github.com/user-attachments/assets/2da27b28-22b9-4eef-b4f6-39f55e0a4f73) / [after](https://github.com/user-attachments/assets/3d07067e-6a0d-49dd-a3c0-7728572a9046))
- Changed media queries for action buttons on the dashboard, allowing them to fit properly on mobile devices ([before](https://github.com/user-attachments/assets/5536cfb4-4269-44b9-aedc-d5fb72c86f5e) / [after](https://github.com/user-attachments/assets/50ad3ddb-b3df-4747-97ae-be61b0a9ce35))
- Removed …
=> style: improve responsiveness and ux

intranet/templates/dashboard/dashboard.html
- Only have the announcement header for senior email forwarding show on the first page of the dashboard announcements
The senior email forwarding announcement currently shows on pages it shouldn't, like the club announcements page (see image below). This fixes that by only showing it on the main dashboard page.
=> fix(dash): fix visibility of senior email forwarding header

intranet/settings/__init__.py
- Changed HOCO_START_DATE to 9/28 (same as end date) to shut off the hoco banner on Ion temporarily
Right now the homecoming site has not been reset yet, so the data displayed is data from last year, and should not be up on Ion.
=> Hoco banner temp shutoff

config/docker/secret.py, intranet/settings/__init__.py, intranet/settings/ci_secret.py
Settings in production is a little different and necessitates this.
Allow early import via method (in production, moving the `from .secret import *` causes a circular import since the settings secret.py relies on already defined settings in `__init__.py`)
=> refactor(settings): revert back to * import and use method for oidc key

intranet/middleware/url_slashes.py
The url https://ion.tjhsst.edu/oauth/.well-known/jwks.json should be accessible for OIDC authentication, but currently the middleware prevents that by forcing a trailing slash.
=> fix(middleware): allow jwks.json to go to django-oauth-toolkit

intranet/static/themes/snow/snow.js
- Encode dayStreak cookie with base64
Currently, the dayStreak cookie used for the snow theme is plaintext and can be edited through inspect element.
=> Encode dayStreak cookie with base64
