tjcsl/ion

docs/setup/sandbox.rst
Following the setup instructions word-for-word didn't work out, so here's what did.
If I haven't introduced myself, Ethan: hi, call me Adam or Zeal, I don't care, I'm a junior, not a sysadmin, have hung out in CSL since Fox dragged me there in 2012 and will try to contribute more than a four-line diff once it's not 1:29 AM any more.
=> Updating docs to reflect what worked today

intranet/apps/files/forms.py, intranet/apps/files/views.py, intranet/templates/files/directory.html, intranet/templates/files/upload.html
Let admins access other directories
=> Admins can access anything, fix #218

fixtures/create_fixtures.py, intranet/apps/announcements/views.py, intranet/apps/auth/backends.py, intranet/static/css/login.css
Fixed CSS Issue on Some Mobile Devices
Fixed Repetitive `redirect("index")` in `views.py`
Fixed Docstrings
=> Minor Changes

intranet/apps/eighth/serializers.py, intranet/apps/notifications/views.py, intranet/apps/users/views.py, intranet/static/js/common.js, intranet/static/js/dashboard/announcements.js, intranet/static/js/eighth/signup.js, intranet/static/js/eighth/signup.search.js, intranet/static/js/schedule.js, intranet/templates/credits.html, intranet/utils/ical.py
Fixed repetitive code in Javascript and Python
=> Javascript and Python Changes

intranet/apps/auth/forms.py, intranet/templates/page_with_header.html, intranet/templates/schedule/view.html
Some Accessibility Fixes and Template Fixes
=> Minor Fixes

intranet/templates/announcements/emails/admin_approve.html, intranet/templates/announcements/emails/announcement_approved.html, intranet/templates/announcements/emails/announcement_posted.html, intranet/templates/announcements/emails/teacher_approve.html, intranet/templates/eighth/emails/absence.html, intranet/templates/eighth/emails/signup_status.html, intranet/templates/eighth/emails/signup_status.txt, intranet/templates/email_footer.html, intranet/templates/email_header.html, intranet/templates/events/emails/admin_approve.html
https://developers.google.com/gmail/markup/reference/go-to-action
=> Added Go-To Actions for Gmail

intranet/apps/eighth/serializers.py, intranet/apps/eighth/views/api.py
- Added block_letter to response
- Now results are sorted by date and then block
=> signups/user API tweaks

intranet/apps/auth/forms.py, intranet/templates/dashboard/birthdays.html, intranet/templates/eighth/take_attendance.html, intranet/templates/files/auth.html, intranet/templates/page_with_header.html, intranet/templates/preferences/preferences.html, intranet/templates/serviceworker.js
Second Try at this Pull Request (#385)
=> Improved Accessibility

docs/setup/postinstall.rst
Added instructions to the post install guide on how to add file systems to the Files page
=> Added files setup documentation

intranet/static/css/files.css, intranet/static/js/files.js, intranet/templates/files/directory.html
added feature to upload multiple files on drag and drop
if browser support is not available, then nothing will happen and drag and drop instructions will be hidden
=> added drag and drop to upload

docs/developing/testing.rst, intranet/apps/files/tests.py, intranet/apps/files/urls.py, intranet/apps/files/views.py, intranet/static/css/files.css, intranet/templates/files/delete.html, intranet/templates/files/directory.html
=> Added delete function to filecenter

intranet/templates/files/directory.html
the previous directory and empty directory had only 1 td tag, changed to 3 so it doesn't look weird
=> fixed table, added date modified for folders

intranet/apps/eighth/exceptions.py, intranet/apps/eighth/forms/admin/activities.py, intranet/apps/eighth/migrations/0035_eighthactivity_blacklist.py, intranet/apps/eighth/models.py, intranet/apps/eighth/tests.py, intranet/static/js/eighth/admin.js
users will not be able to sign up for an activity if they are on the activity's blacklist
fixes issue #387
=> added activity blacklisting

intranet/apps/files/views.py
=> added error message on delete permission error

intranet/apps/api/authentication.py, intranet/apps/api/tests.py, intranet/apps/auth/backends.py, intranet/apps/auth/views.py, intranet/apps/eighth/tests.py, intranet/apps/users/models.py, intranet/middleware/environment.py, intranet/middleware/ldap_db.py, intranet/settings/__init__.py, intranet/settings/travis_secret.py
Shouldn't break anything, but since it's messing with auth, I wanted another set of eyes on it.
=> Auth refactor

intranet/static/js/common.nav.js, intranet/static/js/eighth/signupUI.js, intranet/templates/page_with_nav.html
decided not to use library because too many extra features
tested on chrome on android, should work for modern mobile browsers
=> added swipe left/right to close/open navbar

intranet/static/css/signage.base.scss, intranet/static/css/signage.touch.scss, intranet/templates/signage/touch.html
@willzhang05 I believe @jwoglom had some comments on this change, so I broke it out into a new branch to ease review.
=> Cleaned up calendar in signage and realigned nav buttons

intranet/apps/eighth/models.py, intranet/templates/eighth/emails/waitlist.html, intranet/templates/eighth/emails/waitlist.txt
Changed Waitlist system into notification system
=> Updated Notification System changing Waitlist, edited Waitlist texts

intranet/templates/users/profile.html
=> Do not display None as phone number (Fix #535)

intranet/settings/__init__.py, intranet/static/css/signage.base.scss, intranet/static/css/signage.page.scss
Micro-optimization. No idea if anything else needs to be done.
=> Hide scrollbars on signage

intranet/apps/announcements/notifications.py
Self explanatory
cc: @ovkulkarni
=> Ignore email/twitter notifications in development

intranet/static/js/files.js
for drag and drop uploads
Fixes #538
=> Force timeago update

intranet/apps/eighth/tests.py, intranet/apps/eighth/views/admin/general.py, intranet/apps/eighth/views/admin/groups.py, intranet/apps/eighth/views/admin/sponsors.py
* Removes form pickling
* Adds appropriate test cases
Obsoletes #588; fixes Sentry ION-9X and ION-9Z.
=> Fix add sponsor

intranet/templates/schedule/admin_daytype.html
See #594 for an explanation of why this is worthy of a PR.
=> Set type attribute for "Day Name" field on schedule daytype field

intranet/apps/eighth/tests.py, intranet/apps/eighth/views/activities.py
=> Omit by default past years' blocks from activity page

intranet/apps/eighth/tests.py, intranet/apps/eighth/views/activities.py
I didn't quite perform date calculations correctly in #622, and the timezone issues are currently causing the build to fail in #587 because (as of the creation of this PR) it's after midnight UTC but before midnight EDT. This PR should fix that.
=> Fix bugs accidentally introduced in #622

intranet/static/js/schedule.js, intranet/templates/schedule/month.html, intranet/templates/schedule/week.html
Self-explanatory. The calendar view appears to have been added almost as an afterthought, so it's not surprising that there are bugs.
=> In the calendar view, only display 'Passing' period for today

.pylintrc, intranet/apps/announcements/notifications.py, intranet/apps/api/tests.py, intranet/apps/api/views.py, intranet/apps/eighth/models.py, intranet/apps/eighth/views/admin/activities.py, intranet/apps/eighth/views/admin/maintenance.py, intranet/apps/eighth/views/routers.py, intranet/apps/files/tests.py, intranet/apps/users/tests.py, intranet/asgi.py, intranet/routing.py, intranet/settings/__init__.py
Continuation of #610 and #611.
=> Clean up parts of the codebase

intranet/apps/events/forms.py, intranet/apps/polls/forms.py, intranet/apps/users/models.py
Same line as #635/#611/#610, but split from #635 because these are slightly more involved.
=> Refactor poll and event forms; override User.get_full_name()

intranet/apps/api/tests.py, intranet/apps/eighth/views/api.py
Fixes #620, plus a semi-related issue.
=> Eighth API fixes

intranet/apps/api/tests.py, intranet/apps/bus/models.py, intranet/apps/eighth/models.py, intranet/apps/eighth/tests.py, intranet/apps/eighth/views/api.py, intranet/apps/users/models.py
A bit more involved than the "Clean up codebase" series, but still small changes.
=> Improve code quality

.pylintrc, intranet/apps/dashboard/views.py, intranet/apps/eighth/models.py, intranet/apps/eighth/views/signup.py
Part of the #610/#611/#635/#637/#641 chain.
=> Clean up codebase

intranet/apps/eighth/models.py, intranet/apps/eighth/tests.py, intranet/apps/eighth/views/admin/activities.py, intranet/apps/eighth/views/admin/scheduling.py
Part of the #610/#611/#635/#637/#641/#645 chain.
@theo-o: Unlike previous PRs of this type, this PR refactors significant sections of code that are critical to Ion's functionality. Please review carefully.
=> Clean up parts of codebase

.pylintrc, intranet/apps/announcements/api.py, intranet/apps/auth/helpers.py, intranet/apps/oauth/views.py, intranet/middleware/profiler.py
This is a collection of several tweaks to the Pylint configuration that make it a little saner.
=> Pylint tweaks

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
#654 and #655 each only change one file and are currently broken.
=> Bump django from 1.11.21 to 1.11.22

.travis.yml, intranet/apps/eighth/models.py, intranet/apps/eighth/views/activities.py, intranet/apps/eighth/views/admin/groups.py, intranet/apps/users/models.py, intranet/apps/users/tests.py, intranet/apps/welcome/views.py, intranet/utils/helpers.py
Also fix some code styling that would have made it fail.
=> Add flake8 check back

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.middleware.rst, intranet/middleware/dark_mode.py, intranet/settings/__init__.py, intranet/utils/helpers.py
This is done by setting a cookie when they log in and checking it when they log out.
=> Remember if a user has enabled dark mode even after logout

Ion.egg-info/SOURCES.txt, intranet/static/css/oauth.scss, intranet/templates/docs/accounts.html, intranet/templates/oauth2_provider/base.html, intranet/templates/robots.txt, intranet/urls.py
Related to https://gitlab.tjhsst.edu/sysadmins/infrastructure/general/issues/86 (internal).
=> Add rought draft of CSL account documentation

intranet/apps/eighth/views/admin/attendance.py, intranet/templates/eighth/admin/delinquent_students.html
to not display nondelinquent students. Also lowers default upper limit
to 100.
=> refactor(eighth): refactor delinquent_students_view

intranet/static/css/dark/base.scss, intranet/static/css/dark/nav.scss
Just a few small color tweaks.
=> Dark mode styling tweaks

intranet/apps/eighth/models.py
=> Add a few more eighth model docs

intranet/apps/announcements/models.py, intranet/apps/users/models.py, intranet/apps/users/tests.py, intranet/static/css/announcements.form.scss, intranet/static/css/base.scss, intranet/static/css/polls.form.scss, intranet/templates/announcements/add_modify.html, intranet/templates/events/add_modify.html, intranet/templates/events/delete.html, intranet/templates/events/event.html, intranet/templates/polls/add_modify.html, intranet/templates/polls/delete.html
Resolves #618 (announcement author nickname), fixes #616, fixes #350 (both checkbox alignment).
Also cleans the pages up a little and makes the "Delete" buttons red for contrast.
=> Announcements/polls/events add/modify/delete page fixes and tweaks

intranet/apps/itemreg/forms.py, intranet/apps/itemreg/models.py, intranet/apps/itemreg/templatetags/texthighlight.py, intranet/apps/itemreg/urls.py, intranet/apps/itemreg/views.py, intranet/static/css/base.scss, intranet/static/css/lostfound.scss, intranet/templates/itemreg/home.html, intranet/templates/itemreg/register_form.html, intranet/templates/itemreg/search.html
Includes a bug fix, a security fix, and some general cleanup.
=> Cleanup itemreg app

intranet/static/css/base.scss, intranet/static/css/dashboard.widgets.scss, intranet/static/css/schedule.scss, intranet/templates/dashboard/eighth_info.html, intranet/templates/dashboard/links.html, intranet/templates/schedule/admin_home.html, intranet/templates/schedule/month.html, intranet/templates/schedule/week.html
=> Templates and styling fixes and tweaks

intranet/templates/announcements/add_modify.html, intranet/templates/announcements/approve.html, intranet/templates/announcements/emails/announcement_approved.html, intranet/templates/announcements/emails/announcement_approved.txt, intranet/templates/announcements/emails/announcement_posted.html, intranet/templates/announcements/emails/announcement_posted.txt
author for announcements in templates
=> fix(announcements): use get_author in displaying

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/models.py, intranet/apps/eighth/notifications.py, intranet/apps/eighth/views/admin/scheduling.py, intranet/templates/eighth/emails/activity_cancelled.html, intranet/templates/eighth/emails/activity_cancelled.txt
=> Notify users when activities they are signed up for are cancelled

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/notifications.py, intranet/apps/eighth/views/admin/activities.py, intranet/apps/eighth/views/admin/scheduling.py, intranet/templates/eighth/emails/room_changed_activity.html, intranet/templates/eighth/emails/room_changed_activity.txt, intranet/templates/eighth/emails/room_changed_single.html, intranet/templates/eighth/emails/room_changed_single.txt, intranet/utils/helpers.py
Closes #710.
@theo-o: I have tested this, but I don't want to find out there's a bug _after_ we accidentally spam several hundred users. :fire: If you don't have time to test this properly, please just wait on it. It's not urgent.
=> Notify students about room changes

intranet/apps/context_processors.py, intranet/apps/emerg/views.py, intranet/settings/__init__.py, intranet/static/css/eighth.profile.scss, intranet/static/js/eighth/signup.js, intranet/static/js/login.js, intranet/templates/eighth/profile_signup.html, intranet/templates/oauth2_provider/authorized-tokens.html
@theo-o: Most of these are pretty simple, but the TLS fix has an interesting past -- it's been fixed twice, only to be reverted almost immediately -- and I'm not entirely sure why. It works fine in local testing, but when you deploy to production you might want to send a test email just to be sure.
=> Miscellaneous fixes

intranet/apps/announcements/views.py, intranet/apps/auth/views.py, intranet/apps/context_processors.py, intranet/apps/dashboard/views.py, intranet/apps/eighth/management/commands/signup_status_email.py, intranet/apps/eighth/utils.py, intranet/apps/eighth/views/activities.py, intranet/apps/eighth/views/admin/maintenance.py, intranet/apps/eighth/views/attendance.py, intranet/apps/eighth/views/profile.py, intranet/apps/emerg/views.py, intranet/apps/schedule/notifications.py, intranet/apps/schedule/views.py, intranet/apps/templatetags/dates.py, intranet/apps/users/models.py, intranet/middleware/access_log.py, intranet/utils/date.py, intranet/utils/deletion.py, intranet/utils/helpers.py
@theo-o: The build passes, and I've gone through and I don't *think* this will break anything, but this is another one that will require careful review before merging.
=> Switch from datetime to django.utils.timezone

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.error.rst, intranet/apps/context_processors.py, intranet/apps/error/tests.py
Fixes a bug introduced in 55a870b.
=> Fix: Fail gracefully on 404s

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, intranet/settings/__init__.py, requirements.txt
* Adds [Celery](https://docs.sentry.io/platforms/python/celery/) and [Redis](https://docs.sentry.io/platforms/python/redis/) Sentry integrations.
* Also bumps sentry-sdk
Fixes #745
=> Update sentry integrations

intranet/templates/eighth/admin/no_signups_roster.html
=> Add dark mode to no signups roster view

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/discussion.md, .github/ISSUE_TEMPLATE/documentation_needed.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/refactor_needed.md, .github/ISSUE_TEMPLATE/tests_needed.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .pylintrc, CONTRIBUTING.md, Ion.egg-info/SOURCES.txt, SECURITY.md, intranet/apps/eighth/forms/admin/activities.py, intranet/static/css/eighth.profile.scss, intranet/templates/eighth/edit_profile.html
- Add issue and PR templates
- Add contributing guidelines
- Styling tweaks
- Switch Pylint job count to 0 for autodetection
=> Bug fixes and tweaks

intranet/apps/groups/forms.py, intranet/apps/groups/models.py, intranet/apps/groups/views.py, pyproject.toml
- Implements more efficient `student_visible()`
- Blackifies groups app
- Adds excludes to `pyproject.toml`
=> Improve groups app

intranet/apps/eighth/views/admin/groups.py
- Check if the user is in a group before attempting to add them to it
Bug fix.
=> Fix user already being in group in upload group view

intranet/apps/auth/views.py, intranet/apps/events/models.py, intranet/apps/preferences/views.py, intranet/apps/search/views.py, intranet/settings/__init__.py
- Cache user dark mode properties
- Cache sports/school event lists on login page
Heavy load on Ion over the past week
=> Improve caching

intranet/apps/auth/backends.py, intranet/apps/auth/views.py, intranet/apps/eighth/models.py, intranet/apps/eighth/views/signup.py
- Collect Kerberos authentication Prometheus metrics (closes #796 and #774)
- Collect eighth signup Prometheus metrics (closes #775)
We need more Prometheus metrics.
=> Add Prometheus metrics

Ion.egg-info/SOURCES.txt, intranet/templates/docs/terminology.html, intranet/urls.py
- Adds a webpage describing the proper use of Ion.
Related to #805 (see issue for context)
=> feat(docs): add terminology docs

intranet/templates/dashboard/links.html
feat: add link to the FCPS Challenge Success website in "Useful Links"
This was a request from the Challenge Success team. 
POC: Mr. Forgash (mforgash@fcps.edu)
=> feat: add link to the FCPS Challenge Success website in "Useful Links"

intranet/apps/auth/views.py, intranet/apps/eighth/models.py, intranet/apps/polls/models.py, intranet/apps/polls/tests.py, intranet/apps/users/models.py, intranet/apps/users/tests.py
- Respect user birthday permissions in dashboard birthday widget
- Improve efficiency of eighth lunch redirect check
- Respect `Poll.visible` when checking visible poll list
- Improve efficiency of `User.tj_email` slightly
In addition, the following methods were refactored to reduce the number of queries and had tests added:
- `UserManager.user_with_name()`
- `UserManager.get_teachers()`
- `UserManager.get_teachers_sorted()`
- `User.signed_up_today()`
- `Poll.has_unvoted_polls()`
- `Poll.can_vote()`
Reduces the number of database queries, adds tests, and respects permissions properly.
=> Improve database query handling

intranet/apps/printing/views.py
- Tweak exception formatting
- Add an additional test for invalid page ranges
- General cleanup
The `printing` module is somewhat hacky (as are most Python programs that parse the output of other programs as an integral part of their functionality). This PR cleans it up a bit.
=> Clean up printing module

intranet/static/js/bus.js
- Set new reconnecting websocket options for bus
Sets some saner defaults
=> Set new reconnecting websocket options for bus

intranet/apps/events/forms.py
- disable groups field in events request form when not admin (Fixes #782) 
Fixes a bug
=> fix(events): disable groups field in events request form when not admin

.travis.yml, intranet/apps/dashboard/views.py
- Downgrade to pylint 2.3.1 (fixes build)
See #829.
=> Travis: Downgrade to pylint 2.3.1

intranet/templates/preferences/preferences.html
- Move bus route and mail forwarding to the top
- Add secondary save button
-
=> refactor(preferences): reorganize preferences page

intranet/templates/dashboard/dashboard.html
- Move birthdays to the bottom of dashboard
- Fixes #609
-
=> refactor(dashboard): move birthdays down in the dashboard

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.eighth.views.rst, intranet/apps/eighth/models.py, intranet/apps/eighth/urls.py, intranet/apps/eighth/views/monitoring.py, intranet/settings/__init__.py, intranet/templates/eighth/prometheus-metrics.txt
- Fix eighth Prometheus metrics by moving them to a new custom view (will require changes to the production Prometheus configuration)
- Add metrics to count the number of duplicate signups
Improves the state of Ion Prometheus metrics
=> Improve Prometheus metrics

intranet/apps/preferences/views.py, intranet/templates/preferences/preferences.html
- Disables privacy options form.
- 
- 
The form is currently obsolete.
=> Remove privacy form

intranet/apps/eighth/models.py
- Add more logging to `EighthScheduledActivity.add_user()`
We are seeing duplicate signups appear (see #629). However, investigation of each case has not been fruitful -- we just don't have much information about what actions the user took leading up to the creation of the duplicate signup. This is designed to help fix that.
Note: I have tested this in the following cases:
- Signing up for a single-block activity (not being signed up for anything else that block)
- Signing up for a double-block activity (not being signed up for anything else that block)
- Switching from a single-block activity to another single-block activity
- Switching from a double-block activity to another double-block activity
- Switching from a single-block activity to a double-block activity
- Switching from a …
=> Add logging to EighthScheduledActivity.add_user()

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.eighth.management.commands.rst, intranet/apps/eighth/management/commands/update_counselors.py
- Adds a management script that updates counselors associated with a user
A useful script to update counselors based on updated information. This is especially useful when the counselor for many students changes.
=> Add counselor update management script

intranet/apps/eighth/models.py, intranet/apps/users/models.py, intranet/celery.py, intranet/middleware/profiler.py, intranet/utils/deletion.py
- ci(Travis): disable new Pylint checks
Currently, the Pylint build is broken. This fixes that.
=> ci(Travis): disable new Pylint checks

intranet/apps/eighth/models.py
- Add more logs to `EighthScheduledActivity.add_user()`, `EighthSignup.create_signup()`, and `EighthSignup.save()`
Continuation of #847. Tested for the same cases.
=> Add more logs to EighthScheduledActivity.add_user(), EighthSignup.create_signup(), and EighthSignup.save()

Ion.egg-info/SOURCES.txt, intranet/apps/auth/views.py, intranet/static/img/logos/Login-Logo-halloween.svg, intranet/static/themes/halloween/halloween.css, intranet/static/themes/halloween/halloween.js, intranet/utils/helpers.py
- Add Halloween theme
We should have more seasonal themes.
=> Add Halloween theme

intranet/static/css/dark/dashboard.scss, intranet/static/css/dashboard.scss, intranet/static/js/dashboard/announcements.js
- Partially collapse long announcements (closes #869)
See #869
=> Partially collapse long announcements

intranet/templates/page_with_header.html
=> feat(nav): add logout button; Closes #772

intranet/apps/context_processors.py, intranet/apps/features/urls.py, intranet/apps/groups/tests.py, intranet/static/css/dark/login.scss
- Make dark mode work well with snow theme
- Remove Django 1.x-isms
- Test unauthenticated access to group view/add pages
- The snow theme will be enabled within a month, and we don't want the login page to be broken for users who also have dark mode enabled.
- #800
- #361
=> Fixes and tests

intranet/apps/polls/views.py
- Attempt to handle duplicate Answers
- 
- 
Duplicate `Answer` objects are causing things to break.
=> fix(polls): attempt to handle duplicate Answers

intranet/apps/eighth/views/attendance.py, intranet/settings/__init__.py, intranet/templates/welcome/teacher.html
- Allow configuration of 8th period coordinator's name
- 
- 
Currently, the name is hardcoded which is suboptimal.
=> refactor: allow configuration of Eighth Period Coordinator name

Ion.egg-info/requires.txt, docs/developing/requirements.rst, docs/rtd-requirements.txt, requirements.txt
- Update a lot of packages
- 
- 
Many of our direct dependencies are out-of-date.
=> Package upgrades

intranet/apps/eighth/models.py
- Ignore cache in signup duplicate checks
Should help with #629.
=> Ignore cache in signup duplicate checks

intranet/apps/eighth/models.py, intranet/apps/printing/views.py, intranet/apps/users/models.py, intranet/apps/users/tests.py, intranet/templates/meta.html, intranet/templates/polls/results.html
- Use case-insensitive comparisons with emails
- Improve efficiency of email properties slightly
- Remove redundant `User.male`/`User.female` attributes in favor of `User.is_male` and `User.is_female`
- Add more type annotations and fix incorrect type annotations
- Make sure `User.__str__()` always returns a string
- Return `None` instead of `False` for errors in `printing` helpers
- Remove unused `User.startpage` property
- Remove unneeded favicon references
A lot of miscellaneous fixes. Should be audited carefully.
=> Miscellaneous cleanup

intranet/apps/printing/views.py, intranet/settings/__init__.py
- Add logging and breadcrumbs to printing app; improve error messages
- Add more type annotations and docstrings to printing app
- Lower printer list cache expiration time
=> Printing tweaks

Ion.egg-info/SOURCES.txt, intranet/apps/signage/urls.py, intranet/apps/signage/views.py, intranet/templates/signage/pages/eighth.html
- Add signage eighth period page (closes #822)
Requested by eighth period office (see #822)
=> Add signage eighth period page

intranet/static/js/signage.js
- Strip links more aggressively in signage
The current system does not appear to work.
=> Strip links more aggressively in signage

intranet/templates/auth/login.html
- Move remember me checkbox below login button (closes #908)
As per #908:
> It looks better there.
=> Move remember me checkbox below login button

intranet/templates/page_with_header.html
Fixes #764
- Add link to OAuth page to dropdown
- 
-
=> refactor(OAuth): Add link to OAuth page to dropdown

intranet/apps/eighth/models.py
- Disable cache for `add_user()` activity capacity check
- Lock on the `User` and the `EighthScheduledActivity` in `add_user()`
#629 explains the problems with duplicate signups. Over-capacity signups (users overfilling an activity by signing up at the same time) are also a serious issue that we should prevent.
=> Attempt to block over-capacity and duplicate signups

intranet/templates/emailfwd/senior_forward.html
- Rephrase senior email forwarding message
The senior email forwarding message omits several important details about senior mail forwarding.
=> Rephrase senior email forwarding message

Vagrantfile, docs/setup/vagrant.rst, intranet/static/css/dark/schedule.scss, intranet/templates/signage/base.html
- Don't use bindfs in Vagrant development environments (it's not necessary with our current setup)
- Display "other" days in white text on schedule admin page
- Add schedule JS to signage page
All small tweaks/fixes.
=> Miscellaneous fixes and tweaks

intranet/templates/signage/pages/bus.html
=> style(signage): fix tjCSL logo positioning on bus page

intranet/templates/dashboard/links.html
=> feat(dashboard): add tjCSL blog link to dashboard

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/tasks.py, intranet/apps/eighth/views/admin/groups.py, intranet/templates/eighth/admin/sign_up_group.html, intranet/templates/eighth/emails/group_signup_complete.html, intranet/templates/eighth/emails/group_signup_complete.txt, intranet/templates/eighth/emails/group_signup_error.html, intranet/templates/eighth/emails/group_signup_error.txt
- Allow group signups to be run in a Celery task (closes #943)
See #943
=> Allow group signups to be run in a Celery task

intranet/static/css/_colors.scss, intranet/static/css/dark/base.scss, intranet/static/css/dark/cke.scss, intranet/static/css/dark/dashboard.scss, intranet/static/css/dark/dashboard.widgets.scss, intranet/static/css/dark/eighth.signup.scss, intranet/static/css/dark/events.scss, intranet/static/css/dark/files.scss, intranet/static/css/dark/polls.scss, intranet/static/css/dark/sessionmgmt.scss
- Darken borders in dark mode
A lot of people seem to be requesting this.
=> Darken borders in dark mode

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
- Bump bleach from 3.1.0 to 3.1.1
=> Bump bleach from 3.1.0 to 3.1.1

intranet/static/css/dark/eighth.schedule.scss, intranet/static/css/eighth.signup.scss
- Don't show unnecessary scrollbar in activity detail pane
- Fix eighth scheduling page header color in dark mode
Small styling tweaks.
=> Styling tweaks

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.dataimport.management.commands.rst, intranet/apps/dataimport/management/commands/import_users.py
- add import_users management command
- 
-
=> feat(dataimport): add import_users management command

docs/setup/vagrant.rst
Increased clarity of the instructions in files postinstall.rst and vagrant.rst. Also have deleted unnecessary characters in vagrant.rst.
=> docs(setup): increase clarity in instructions

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.dataimport.management.commands.rst, intranet/apps/dataimport/management/commands/import_eighth.py
- add import_eighth management command
- 
-
=> feat(dataimport): add import_eighth management command

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.eighth.management.commands.rst, intranet/apps/eighth/management/commands/dev_create_blocks.py
- generate 8th period blocks for development
- 
-
=> feat(eighth): generate 8th period blocks for development

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/tasks.py, intranet/apps/eighth/urls.py, intranet/apps/eighth/views/attendance.py, intranet/templates/eighth/email_students.html, intranet/templates/eighth/take_attendance.html
- Allow sponsors to email students signed up for a club
See #578
=> Allow sponsors to email students signed up for a club

intranet/static/js/eighth/schedule.js, intranet/templates/eighth/admin/schedule_activity.html
- Ask for confirmation before an admin cancels a sticky activity.
To close issue #876.
=> Warn about effects of cancelling sticky activities.

.travis.yml
- Attempt to fix build for new version of pylint
A new version of Pylint has been released. This PR fixes several issues Pylint finds.
=> Attempt to fix build for new version of pylint

intranet/apps/eighth/views/activities.py, intranet/apps/eighth/views/admin/blocks.py, intranet/apps/users/models.py
- Clean up code to make `flake8` happy
A new version of `flake8` has added some additional tests that fail on our codebase.
=> Clean up code to make flake8 happy

intranet/apps/users/forms.py, intranet/apps/users/models.py, intranet/apps/users/serializers.py, intranet/apps/users/tests.py
- clean up birthday fields and methods from the users model that I had missed earlier
=> fix(birthdays): clean up user birthday fields

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.eighth.management.commands.rst, intranet/apps/eighth/management/commands/signup_statistics.py
- Add signup statistics generation script
This generates the same information as `/eighth/activity/statistics/<id>`, but as a CSV. It also allows for custom filtering of the results.
=> feat(eighth): add signup statistics generation script

intranet/apps/polls/models.py, intranet/apps/polls/tests.py, intranet/templates/polls/poll.html, intranet/templates/polls/results.html
=> feat(polls): add number voted count

docs/developing/oauth.rst
- Revise docs/developing for clarity
The current state of the `python-social-auth` section was somewhat unhelpful, so I revised it to assist future readers.
Note: I redid this because I messed up the commit history in the original PR so I thought it would be easier to just redo it.
=> docs(oauth): updated python-social-auth instructions

Ion.egg-info/SOURCES.txt, intranet/apps/bus/consumers.py, intranet/apps/bus/urls.py, intranet/apps/bus/views.py, intranet/apps/signage/pages.py, intranet/settings/__init__.py, intranet/static/css/bus.scss, intranet/static/js/bus-afternoon.js, intranet/static/js/bus-morning.js, intranet/static/js/bus-shared.js, intranet/templates/bus/bus_head.html, intranet/templates/bus/home.html, intranet/templates/bus/morning.html, intranet/templates/signage/pages/bus.html
The functionality is added to both signage and Ion bus page. At noon, the page switched from the morning to the afternoon bus page to allow for early openings/closing without having to make changes. The pages switch back at midnight.
Let the code review begin.
=> feat(bus): add morning bus arrivial display closes #954

intranet/apps/dataimport/management/commands/delete_users.py
- Fix the `delete_users` command file input
It's broken (one of the command line args don't work properly), this PR fixes it.
=> fix(dataimport): fix delete_users file import

intranet/templates/dashboard/links.html
TJ switched to a new platform for athletics last year.
=> fix(templates): update athletics link

intranet/static/css/page_base.scss, intranet/static/js/common.header.js, intranet/templates/page_with_header.html
closes #904
- Move the "Preferences", "Item Registration", "Lost and Found", and "OAuth" links in the nav dropdown menu under a "User Settings" header that is collapsible.
- To make the dropdown menu more organized and less full (see #904)
=> feat: declutter nav dropdown menu

intranet/apps/dataimport/management/commands/import_students.py
- Add an option to the `import_students` command to create a list of new usernames as they are imported
A list of new usernames is needed for the rest of the new user creation process (AFS homedirs, Kerberos principles, etc.). The import users command generates usernames but doesn't output them anywhere. While we could do a
User.objects.filter(graduation_year={{grad year}})
if we were to add froshmores/users not at the same time as the others, that may cause some problems with scripts and whatnot.
=> feat(dataimport): allow creation of a list of new students' usernames

intranet/apps/eighth/views/attendance.py
- Replace Ion ID with FCPS ID in attendance page
- Addresses Ms. Slonina's request
=> feat(eighth): add student id to attendance page

intranet/apps/eighth/views/attendance.py, intranet/settings/__init__.py, intranet/templates/eighth/take_attendance.html
- Add script behind `is_eighth_admin` (for now) to allow teachers to mass import their students in eighth period.
- For testing, you need to add the following to `secret.py`.
```
BBCU_SCRIPT = """
// DISCLAIMER: This script is provided as is, with no guarantees.<br>
// To add all students, go to https://us.bbcollab.com/collab/ui/scheduler/session, click on the session,<br>
// click on "invitations", then click "invite attendees". Open the console with Ctrl+Shift+J and paste the following.<br><br>
all = +=+=;
var userNumber = 0;
addUser()
function addUser() {
$('#add-enrollment-button').click()
$('#attendee-display-name').val(all[userNumber][0])
$('#attendee-email').val(all[userNumber][1])
$('#attendee-display-name').triggerHandler('change')
$('#attendee-email').triggerHandler('input') …
```
=> feat(eighth): add bbcu import script

intranet/templates/eighth/take_attendance.html
=> feat(eighth): make bbcu link available to staff

intranet/templates/announcements/request.html
=> fix(annoucements): add better guidance for annoucements

docs/setup/postinstall.rst
- Remove broken demo links
- Update argon2 info
=> docs: update links and hashing info

intranet/apps/announcements/forms.py, intranet/apps/announcements/views.py, intranet/templates/announcements/approve.html
- A new form is added so that only admins have the ability to specify notification settings
=> feat(announcement): add custom notification settings

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/tasks.py, intranet/apps/eighth/tests.py, intranet/apps/eighth/views/admin/scheduling.py, intranet/templates/eighth/admin/transfer_students.html, intranet/templates/eighth/emails/transferred_activity.html, intranet/templates/eighth/emails/transferred_activity.txt
=> fix(eighth): fix duplicate signups when transferring students

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/tests.py, intranet/apps/eighth/urls.py, intranet/apps/eighth/views/activities.py, intranet/templates/eighth/admin/dashboard.html, intranet/templates/eighth/admin/multiple_statistics.html
=> feat(eighth): add filtering of students by activity signup

intranet/templates/dashboard/links.html
=> feat(dashboard): add SGA study guides link

intranet/templates/dashboard/links.html
=> fix(dashboard): add newline to links

intranet/apps/announcements/forms.py, intranet/apps/announcements/tests.py, intranet/apps/users/models.py
I've learned to spell announcements correctly!
=> fix(announcements): expand groups allowed to approve announcements

intranet/static/css/bus.scss, intranet/static/js/bus-morning.js, intranet/templates/bus/morning.html
- Just changed the displaying of buses a bit and added a search function when actually selecting the buses.
=> feat(bus): add search for morning buses

intranet/apps/emerg/views.py
FCPS, oh FCPS...
- Add "502 Bad Gateway" to the list of bad emergency messages
=> fix(emerg): add "502 Bad Gateway" to invalid list

intranet/apps/auth/views.py, intranet/apps/dashboard/views.py, intranet/apps/eighth/tests.py, intranet/apps/eighth/views/signup.py
- Redirect to eighth_location view from dashboard instead of upon login
This will ensure that even people who are already logged in are redirected properly
=> fix(eighth): change eighth_location redirect method

intranet/static/css/login.scss, intranet/static/js/login.js, intranet/templates/auth/login.html
- Use javascript and regex to check a user's username upon entry and warn them if it isn't in the correct format 
- Reduce the number of emails about not being to log into Ion
=> feat(auth): warn about incorrect username format

intranet/templates/dashboard/links.html
=> fix(dashboard): change student advocacy link

intranet/apps/eighth/tests.py, intranet/apps/eighth/views/attendance.py, intranet/static/css/eighth.attendance.scss, intranet/templates/eighth/take_attendance.html
=> feat(eighth): allow attendance taking with google meet csv

intranet/apps/eighth/tests.py, intranet/apps/eighth/views/attendance.py
- Fix the attendance bug described [here](https://github.com/tjcsl/ion/pull/1082/files#r572579274). Ref. #1082 and 5c7b22c41e1eb8b00bfa445178d33bafbd111eba.
- Add unit tests for taking attendance "normally".
Attendance can't be taken after 5c7b22c41e1eb8b00bfa445178d33bafbd111eba is deployed.
=> fix/test(eighth): fix attendance bug, add unit tests for attendance

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
=> chore: bump cryptography

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.eighth.rst, docs/sourcedoc/intranet.apps.eighth.tests.rst, intranet/apps/eighth/tests/test_admin.py, intranet/apps/eighth/tests/test_general.py, intranet/apps/eighth/tests/test_others.py, intranet/apps/eighth/views/attendance.py
=> test(eighth): add rooms, attendance and signup tests

intranet/apps/parking/tests.py, intranet/apps/polls/tests.py, intranet/apps/preferences/tests.py, intranet/test/ion_test.py
- Adds some tests for the parking, polls, and preferences apps
- Adds type to `ion_test` module
Self explanatory
=> test: add parking, polls, preferences tests

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.eighth.views.admin.rst, intranet/apps/dashboard/views.py, intranet/apps/eighth/Hybrid-README.rst, intranet/apps/eighth/models.py, intranet/apps/eighth/urls.py, intranet/apps/eighth/views/admin/blocks.py, intranet/apps/eighth/views/admin/general.py, intranet/apps/eighth/views/admin/hybrid.py, intranet/apps/eighth/views/attendance.py, intranet/apps/eighth/views/profile.py, intranet/apps/eighth/views/signup.py, intranet/apps/users/views.py, intranet/settings/__init__.py, intranet/templates/eighth/admin/activities_without_attendance_hybrid.html, intranet/templates/eighth/admin/add_block.html, intranet/templates/eighth/admin/dashboard.html, intranet/templates/eighth/admin/list_sponsors_hybrid.html, intranet/templates/eighth/empty_state.html, intranet/templates/eighth/profile.html, intranet/templates/eighth/profile_signup.html, intranet/templates/eighth/signup.html, intranet/templates/eighth/signup_widget.html, intranet/templates/eighth/sponsor_widget.html, intranet/templates/eighth/take_attendance.html
Read [this file](https://github.com/Laur04/ion/blob/hybrid/intranet/apps/eighth/Hybrid-README.rst) for details. 
I'm not by any means done with this; I need to run it through with 8PO and probably write some tests. However, the first iteration of the function is here, so test it out and let me know what you think (after reading the above document).
=> feat(eighth): enable hybrid

intranet/apps/eighth/Hybrid-README.rst, intranet/apps/eighth/tasks.py, intranet/apps/eighth/views/admin/blocks.py
- Use celery to sign groups up 
Times out in production
=> fix(eighth): move hybrid block signup to celery

intranet/apps/eighth/views/api.py, intranet/apps/lostfound/views.py, intranet/apps/users/models.py
=> fix(ci): make pylint happy

intranet/apps/eighth/tests/test_general.py, intranet/apps/notifications/emails.py
Tested on `ion-dev` with success.
=> fix(notifications): break up large emails

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.eighth.management.commands.rst, intranet/apps/eighth/management/commands/dev_generate_signups.py
- generate 8th period signups for development
- 
-
=> feat(eighth): generate 8th period signups for development

intranet/apps/announcements/notifications.py
=> fix(announcements): exclude service and alum from emails

intranet/apps/announcements/notifications.py
=> fix(announcements): fix send_all filtering

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/Hybrid-README.rst, intranet/apps/eighth/forms/admin/activities.py, intranet/apps/eighth/forms/admin/blocks.py, intranet/apps/eighth/tasks.py, intranet/apps/eighth/urls.py, intranet/apps/eighth/views/admin/hybrid.py, intranet/apps/eighth/views/signup.py, intranet/templates/eighth/admin/dashboard.html, intranet/templates/eighth/admin/hybrid_groups.html, intranet/templates/eighth/admin/sign_up_group.html, intranet/templates/eighth/emails/group_signup_complete.html, intranet/templates/eighth/emails/group_signup_complete.txt, intranet/templates/eighth/emails/group_signup_error.html, intranet/templates/eighth/emails/group_signup_error.txt, intranet/templates/eighth/location.html
=> hybrid fixes - more to come

intranet/apps/auth/backends.py, intranet/apps/auth/views.py
=> fix(auth): check for incorrect username format

intranet/apps/eighth/Hybrid-README.rst, intranet/static/css/dashboard.widgets.scss
=> fix(hybrid): fix eighth widget format

intranet/apps/announcements/forms.py, intranet/apps/announcements/views.py
=> Announcements

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
- Update dependencies
Our dependencies are getting somewhat out of date.
=> build(deps): bump dependencies

intranet/apps/announcements/tests.py, intranet/apps/dataimport/tests.py, intranet/apps/schedule/tests.py
- Adds unit tests for the `announcements`, `dataimport`, and `schedule` apps.
=> test: add tests for announcements, dataimport, schedule apps

intranet/apps/eighth/tests/admin/test_admin_blocks.py, intranet/apps/eighth/views/admin/blocks.py, intranet/templates/eighth/admin/add_block.html
- Automatically sticky students in the "Withdrawn from TJ" group into "Z - Withdrawn from TJ" activity when 8PO checks a button.- 
8PO asked for it today when I went to talk to them about the 4 days a week transition.
=> feat(eighth): automatically sticky withdrawn students

intranet/apps/eighth/tests/admin/test_admin_activities.py, intranet/apps/eighth/tests/admin/test_admin_scheduling.py, intranet/apps/eighth/views/admin/activities.py, intranet/apps/eighth/views/admin/scheduling.py
=> test(eighth): test notifications for room changes

intranet/apps/eighth/tests/test_signup.py
closes #456
~~PRing this so that Coveralls will run properly, don't bother to review yet.~~
=> test(eighth): improve add_user coverage

intranet/templates/events/event.html
=> fix(events): stop showing 'creator' and 'approved by' that is None

intranet/apps/events/tasks.py
=> fix(events): delete events without a specified time

intranet/templates/emailfwd/senior_forward.html
- Change "By the end of the summer after graduation" to "At the conclusion of the school year"
Makes more sense for seniors (because they won't be coming back to TJ)
=> chore(emailfwd): change senior email forward message

intranet/apps/eighth/views/admin/blocks.py, intranet/templates/eighth/admin/add_block.html
closes #1097
The old PR got very messy so I made this new one. It should include all the proposed changes and be ready to merge.
=> feat(eighth): add ability to set 'signup_time' on eighth block creation

intranet/routing.py
- Fix error caused by #1150 
Changelogs - https://channels.readthedocs.io/en/latest/releases/3.0.0.html
=> build: fix channels 3 error

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
=> build(deps): bump django

intranet/apps/bus/management/commands/import_routes.py, intranet/apps/eighth/tests/test_profile.py, intranet/apps/events/tests.py, intranet/apps/itemreg/views.py, intranet/apps/seniors/management/commands/import_colleges.py, intranet/apps/users/models.py, intranet/apps/users/views.py, intranet/utils/deletion.py
=> fix(ci): fix linting and tests

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.emailfwd.management.commands.rst, docs/sourcedoc/intranet.apps.emailfwd.management.rst, docs/sourcedoc/intranet.apps.emailfwd.rst, intranet/apps/emailfwd/management/commands/get_senior_forwards.py, intranet/apps/emailfwd/tests.py
Closes tjcsl#1152.
- Add `intranet/apps/emailfwd/management/commands/get_senior_forwards.py`, a management command which retrieves and prints senior mail forwards.
- Start work on a test for the management command. This still needs some work - I'm a bit unsure on how to retrieve the output from stdout.
This implementation is based on @etnguyen03's suggestion of outputting formatted strings to stdout.
=> feat(emailfwd): add senior email forwards command

intranet/apps/polls/views.py, intranet/templates/polls/poll.html
Closes #1128
Adds an error message when a user tries to edit their poll after the end date.
=> feat(polls): add error message to modifying polls after end date

intranet/apps/bus/management/commands/import_routes.py, intranet/apps/dataimport/management/commands/delete_users.py, intranet/apps/dataimport/management/commands/import_eighth.py, intranet/apps/dataimport/management/commands/import_photos.py, intranet/apps/dataimport/management/commands/import_staff.py, intranet/apps/dataimport/management/commands/import_students.py, intranet/apps/dataimport/management/commands/import_users.py, intranet/apps/dataimport/tests.py, intranet/apps/eighth/management/commands/signup_statistics.py, intranet/apps/eighth/management/commands/update_counselors.py, intranet/apps/polls/views.py, intranet/apps/printing/views.py, intranet/apps/seniors/management/commands/import_colleges.py, intranet/apps/seniors/tests.py, intranet/apps/users/management/commands/import_groups.py
=> fix(ci): specify encoding for open()

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
=> build(deps): bump pillow

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/tests/admin/test_admin_groups.py, intranet/apps/eighth/urls.py, intranet/apps/eighth/views/admin/groups.py, intranet/templates/eighth/admin/dashboard.html, intranet/templates/eighth/admin/delete_empty_groups.html
=> feat(eighth): add functionality to delete empty groups

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/tests/admin/test_admin_sponsors.py, intranet/apps/eighth/urls.py, intranet/apps/eighth/views/admin/sponsors.py, intranet/templates/eighth/admin/dashboard.html, intranet/templates/eighth/admin/list_sponsor_by_activity.html
=> feat(eighth): add list sponsors page

Ion.egg-info/SOURCES.txt, intranet/apps/eighth/tasks.py, intranet/settings/__init__.py, intranet/templates/eighth/emails/absence_monthly.html, intranet/templates/eighth/emails/absence_monthly.txt
closes #711
- Send a monthly email to everyone with uncleared absences reminding them to get them cleared.
=> feat(eighth): send monthly absence reminder emails

intranet/static/js/hoco_scores.js, intranet/templates/dashboard/dashboard.html, intranet/templates/special/hoco_scores.html
Request for PTSA for upcoming event
=> feat(hoco): add staff grade

intranet/static/themes/april_fools/april_fools.css
=> fix(css): more spring theme detail tweaks

intranet/static/js/eighth/admin.js
- Disable checkboxes when restricted is unselected 
- Closes #1070
=> fix(eighth): disable checkboxes

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
- flower to 1.2.0
- sentry-sdk to 1.9.2
=> build(deps): version bumps

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
=> build(deps): sentry-sdk bump

intranet/static/js/dashboard/common.js, intranet/templates/page_with_header.html, intranet/templates/users/profile.html
- Typing goes to the search bar on dashboard page
- Tab goes to search bar -> View Eighth Profile -> left-side menu on profile page
- Email from Dr. Gabor
=> refactor: focus searchbar on keydown and better tab nav

Ion.egg-info/SOURCES.txt, SETUP.md, scripts/create_users.py
- Script for creating users with specified username
- Supports different types of users and creation of multiple users in one run
- (I also had a script for automatically generating users but I can't seem to find it...I guess just use the Ion fake data one for now)
- Creating users is a little tedious
=> feat(dev): create users script

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
- cryptography to 38.0.1
- ipython to 8.5.0
- ipython to 1.9.8
=> build(deps): version changes

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
=> build(deps): bump certifi

intranet/templates/eighth/signup.html
- Fix issue with activity detail view not showing 
- Also fix only showing waitlist button to admins even if waitlist is enabled
- Bug made detail view and waitlist not work (commit: #1385)
=> fix(eighth): fix activity detail not showing

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, intranet/apps/cslapps/models.py, intranet/apps/cslapps/tests.py, intranet/apps/cslapps/views.py, intranet/apps/emerg/views.py, intranet/settings/__init__.py, intranet/utils/html.py, requirements.txt
- add deps required in `scripts/format.sh`
- add unapplied formatting changes to pass CI
=> fix: add formatting deps and unapplied formatting changes

SETUP.md
(Resolve merge conflicts from #1417 )
- Add documentation on exporting database volume and importing into a different machine
- Add logs command 
- Documenting stuff
=> docs(dev): exporting pgdata

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
=> build(deps): revert django-debug-toolbar

intranet/static/css/dashboard.widgets.scss
- Fix widget links being covered by announcements on home page
- Widget links were broken after a deploy
=> fix: fix widget links

intranet/static/css/signage.base.scss
- Signage bell schedule font size is a little small after recent deploy
=> refactor(signage): increase bell schedule font size

intranet/static/css/polls.scss
=> refactor(polls): add border radius

intranet/templates/polls/poll.html
- Fix bug in poll opening time showing as close time
=> fix(polls): fix opening time

intranet/templates/oauth2_provider/application_detail.html, intranet/templates/oauth2_provider/application_form.html
This reverts commit 53b05eb4cf18e603ab1f89c433b3012c134562be.
- 
- 
-
=> Revert "style(cslapps): added client secret warning for oauth"

intranet/templates/dashboard/admin.html
=> fix(dashboard): fixed admin oauth link

intranet/static/themes/halloween/halloween.css, intranet/static/themes/halloween/halloween.js
- Fix search bar unclickable on mobile
- Change `<meta name="theme-color">` mobile theme color to orange
=> fix(themes): halloween bug fixes

intranet/apps/bus/views.py, intranet/static/css/bus.scss, intranet/static/js/bus-afternoon.js, intranet/static/js/bus-shared.js, intranet/templates/bus/bus_head.html, intranet/templates/bus/home.html, intranet/templates/bus/morning.html
Fix bus map overlaying search bar on mobile
Show bus status as "not arrived yet" if not arrived 5 min before end time
Remove unneeded polls stylesheet
Remove console.log()s
=> fix(bus): mobile zindex, other fixes

intranet/utils/helpers.py
Disable snow until we investigate what's causing the display issues
=> fix(themes): temporarily disable snow

intranet/static/themes/snow/snow.css, intranet/static/themes/snow/snow.js, intranet/utils/helpers.py
feat: winter theme displays on all Ion pages
feat: snow speed and size increases based on days user has viewed theme 
feat: allow option to disable theme
refactor: change theme to start on the first Monday of Dec. and end on the second Monday of Jan.
fix: permanently fix issue that was temporarily fixed by https://github.com/tjcsl/ion/commit/025651006c3c1a232ca50d383cba7a495c44eb97
=> feat(themes): winter theme on all pages

intranet/static/themes/snow/snow.css, intranet/static/themes/snow/snow.js
- make the cookies storing snow streak a little harder to mess with
=> refactor(themes): encode snow cookies, adjust opacity

intranet/static/themes/snow/snow.css, intranet/static/themes/snow/snow.js
=> fix(themes): revert encode snow cookies, adjust opacity"

intranet/apps/eighth/exceptions.py, intranet/apps/eighth/management/commands/dev_generate_signups.py, intranet/apps/eighth/models.py, intranet/apps/eighth/serializers.py, intranet/apps/eighth/tests/test_commands.py, intranet/settings/__init__.py, intranet/templates/eighth/signup.html
- Create a setting field to allow 48-hour presign time to be set differently than midnight.
- Improve descriptions  of 48 hour presign time.
Students should not be awake at midnight signing up, this increases fairness in eighths.
=> implement presign changes

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
- revert cryptography to 37.0.4
deploy doesn't work
=> fix(deps): revert cryptography

Ion.egg-info/SOURCES.txt, SETUP.md, config/create-users.py, config/docker/Dockerfile, config/docker/docker-compose.yml, config/docker/entrypoint.sh, config/docker/initial_setup.sh, intranet/apps/auth/views.py, intranet/apps/django/management/commands/run.py, intranet/middleware/templates.py, intranet/settings/__init__.py, intranet/static/css/base.scss, intranet/static/css/eighth.admin.scss, intranet/static/css/eighth.signup.scss, intranet/utils/helpers.py, requirements-dev.txt, scripts/dev_autoupdate_static.sh
Closes #1425
- Fixes dev env not able to connnect to database
- Makes dev much faster - average page load of 0.5 seconds vs >5 seconds before
- Fix timezones breaking
- Move dev and prod dependencies to separate files
- Automatically restart the web server if it crashes (usually due to a syntax error or other error made while coding)
- Entrypoint wasn't running in right order
- Dev was very very very slow
- Production shouldn't install deps only needed for dev
=> Dev fixes and features

intranet/apps/polls/views.py, intranet/templates/polls/poll.html
=> Polls fixes

config/docker/Dockerfile
fix(dev): make docker build work for arm
=> fix(dev): make docker build work for arm

SETUP.md, config/krb5.conf
- Update Kerberos config
- Add short docs
=> chore(dev): update kerberos config

intranet/apps/polls/views.py, intranet/templates/polls/results.html, intranet/templates/polls/vote.html, intranet/templates/polls/winners.html
- Fix election results breaking when there is only one choice for a question
- Add top choice for other question types in election results view
- Make directions clearer for rank choice (handle edge case of only 1 choice and make it clear the max choices applies only to the current question)
=> Rank choice fixes

intranet/static/js/tjstar_ribbon.js, intranet/templates/special/tjstar_ribbon.html
- tjSTAR ends at 1pm, not 12 (didn't realize there was lunch in the middle)
=> fix(themes): fix tjSTAR end time

intranet/static/js/common.js, intranet/static/js/login.js
- Small fix to login page styling? maybe? I can't replicate on dev
=> refactor(announcements): small warning announcement fix

intranet/static/css/dashboard.widgets.scss
- Small styling fix on widgets (last fix hopefully)
- Dev is being weird and not reflecting what's happening in prod
=> refactor(dashboard): fix widgets styling

Ion.egg-info/requires.txt, docs/rtd-requirements.txt, requirements.txt
- cryptography to 41.0.0
- Django to 3.2.20
- requests to 2.31.0
=> build(deps): final version bumps

.github/CODEOWNERS, Ion.egg-info/PKG-INFO, README.rst
=> chore(docs): transfer

intranet/static/js/hoco_scores.js
- Refresh hoco scores every 5 seconds
- Tweak score box animation slightly
- Resolves #1476 
- A 2-second delay for score boxes syncs their animation with the hoco ribbon
=> feat(hoco): Refresh hoco scores

intranet/apps/enrichment/views.py, intranet/static/js/hoco_scores.js
=> fix(enrichment): add capacity check

intranet/settings/__init__.py
- Change homecoming dates from 9/18-9/23 to 9/16-9/24
Requested by SGA; covers the full range of homecoming events.
=> chore(hoco): extend hoco duration to include weekends

intranet/templates/dashboard/links.html
- Fix Hoco scores embedded breaking ion home page
=> fix(dev): fix hoco scores breaking ion

intranet/apps/eighth/tasks.py, intranet/apps/eighth/views/admin/groups.py, intranet/static/css/eighth.admin.scss, intranet/templates/eighth/admin/distribute_group.html, intranet/templates/eighth/admin/sign_up_group.html
=> feat(eighth): check for users in sticky activities during group signups

intranet/apps/signage/tests.py, intranet/apps/signage/views.py
=> chore(signage): allow TJ ips

intranet/settings/__init__.py
=> chore: update tj IP list

intranet/apps/enrichment/views.py, intranet/static/css/enrichment.scss, intranet/templates/enrichment/enrichment.html, intranet/templates/enrichment/month.html, intranet/templates/enrichment/roster.html, intranet/templates/enrichment/week.html
=> refactor(enrichment): show green text only for current day

intranet/apps/printing/views.py, intranet/templates/printing/print_form.html
=> fix(printing): fix template variable syntax

intranet/templates/dashboard/eighth_info.html
- Add the POI Permission Form to ion's dashboard
=> chore(dashboard): add POI Permission Form Link

intranet/apps/auth/views.py, intranet/settings/__init__.py
=> feat(auth): add cookie to identify authenticated browsers

intranet/apps/dataimport/management/commands/import_photos.py
- Update django command to be able to import staff photos
- Staff photo importing should be automated like with students
=> fix(misc): option to import staff photos

config/docker/Dockerfile
Added libxml2-dev libxslt-dev to the apk
=> fix(dev): add packages to dockerfile apk

intranet/templates/dashboard/links.html
=> chore(dashboard): update report concern form

intranet/static/themes/april_fools/april_fools.js, intranet/utils/helpers.py
- April Fools 2024 part 2
April Fools
=> April Fools 2024 (part 2)

config/scripts/create_users.py
- Update the create_users.py type annotations to conform to python3.8 (use " " around annotations)
=> fix(dev): update type annotations for python3.8

intranet/apps/notifications/emails.py
- fix formatting
- 
- 
make CI pass
=> chore(ci): fix formatting on emails.py

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.templatetags.rst, intranet/apps/dashboard/views.py, intranet/apps/templatetags/paginate.py, intranet/static/css/dark/dashboard.widgets.scss, intranet/static/css/dashboard.widgets.scss, intranet/static/js/dashboard/common.js, intranet/templates/dashboard/dashboard.html
Closes #1604 
Has support for light mode with grey text color
Note: I will rebase with `dev` after the PR is approved.
=> feat(dashboard): sort archived announcements by expiry date

Ion.egg-info/SOURCES.txt, docs/sourcedoc/intranet.apps.dataimport.management.commands.rst, intranet/apps/dataimport/management/commands/import_tj_star.py, intranet/templates/eighth/signup.html
- Add manage.py management command to import tj star data into ion from a csv
- manually entering ~150 blocks worth of tj star data by hand is lunacy
=> feat: add tj star management command

intranet/apps/eighth/views/attendance.py
- Add show_all_blocks GET parameter to attendance form
- Start 8th block selection list at the correct starting date, using this parameter
A show_all_blocks parameter is consistent with the 8th period block selection form. By adding the option to begin blocks at the beginning of the school year, blocks from the past will appear in the list when selected in the form from before. This eliminates the UI bug that occurred when selecting an 8th period in the past.
=> fix(eighth): display correct 8th period block (closes #1660)

.github/workflows/ci.yml, ci/spec.yml
a dependency of sass requires nodejs 14+
=> ci: fix sass error

intranet/apps/eighth/models.py
I believe this bug emerged because `QuerySet` is stateful, so a `self.sticky_students.all()` was the same value as `.set(users)`
=> fix: send out emails when stickied/unstickied

intranet/apps/eighth/models.py, intranet/templates/eighth/emails/students_stickied.html, intranet/templates/eighth/emails/students_stickied.txt, intranet/templates/eighth/emails/students_unstickied.html, intranet/templates/eighth/emails/students_unstickied.txt
I don't think I was sane when I wrote the template.
=> fix: invalid template rendering for individual sticky email

.github/workflows/ci.yml, ci/spec.yml
Hopefully fixes the errors in #1733
=> chore: bump github action versions

intranet/templates/dashboard/links.html
=> chore: add parking pass request form

intranet/templates/eighth/take_attendance.html
=> fix(eighth): reenable take attendance button

intranet/templates/dashboard/links.html
=> chore: remove integrity violation form

intranet/templates/dashboard/links.html
=> chore: stylizing for tjtoday
